### ISSUE TITLE
nw-builder always redownloads nw.js binaries

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nwutils/nw-builder#1037]
### Issue Type

- [x] Bug Report

### Current/Missing Behaviour

The most basic run of the builder always redownloads nw.js ignoring its own cache, which causes slow startups (5+ mins). The redownloads can be observed by node.js network activity + file update changes on cached zip files.

```js
builder = nwbuild({
  mode: "run",
  srcDir: "./",
  version: '0.84.0',
  glob: false,
});
```

### Expected/Proposed Behaviour

`nw-builder` must not redownload nw.js if it is already present in its cache directory.

### Additional Info

- Package version: v4.6.0
- Operating System: Windows
- Node version: v20.7.0
- NW.js version: 0.84.0/0.83.0
- Repro link: see the issue

**Comment by ayushmanchhabra** [comment]
@CosmoMyzrailGorynych please try v4.6.1

**Comment by CosmoMyzrailGorynych** [comment]
Confirming that the issue is fixed in v4.6.1.

**Comment by marc7000** [comment]
I can't confirm that the issue is fixed.

- Package version: v4.13.8
- Operating System: macOS 14.7.4
- Node version: v20.5.0
- NW.js version: 0.97.0

On every build the nw-builder always redownloads nw.js binaries.

**Comment by marc7000** [comment]
@ayushmanchhabra Ok my mistake it works as expected, only if you delete the downloaded archive manually, it is downloaded again although the unpacked archive folder exists.

**Comment by ayushmanchhabra** [comment]
> [@ayushmanchhabra](https://github.com/ayushmanchhabra) Ok my mistake it works as expected, only if you delete the downloaded archive manually, it is downloaded again although the unpacked archive folder exists.

@marc7000 The unpacked archive stays until you specify the `--cache=false`, after which it is deleted and redownloaded.
