### ISSUE TITLE
`build` changes cwd

### ISSUE THREAD

**Issue by breavyn** [nwutils/nw-builder#1186]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

Calling `nwbuild` with `mode: "build"` and  `manageManifest` will change the processes cwd to use the package manager. This requires the caller to save and restore the cwd when using `nwbuild`.

https://github.com/nwutils/nw-builder/blob/8f4e07dfbda348fcc832694d346be7616bfb1f4b/src/bld.js#L233

A similar issue exists here also. https://github.com/nwutils/nw-builder/blob/8f4e07dfbda348fcc832694d346be7616bfb1f4b/src/bld.js#L421

### Expected/Proposed Behaviour

The package manager should be executed with the needed cwd, without changing the calling processes cwd.

I can submit a PR if desired.

**Comment by ayushmanchhabra** [comment]
@breavyn PR would be great. But before that would like to understand how this is a bug? As in what behaviour does this lead to which it should not?

**Comment by breavyn** [comment]
The nwjs application itself is built correctly. However, silently changing the cwd is hostile to users trying to call `nwbuild` from a script. It causes any further filesystem related operations to have unintended outcomes.

I propose either not changing the cwd in the first place, which is a trivial change. Or clearly documenting that this is intended behaviour, suggesting the user save and restore the cwd themselves if needed.

```javascript
const cwd = process.cwd();
await nwbuild({...});
process.chdir(cwd);
```

Keeping in mind changing this behaviour would break scripts relying on the cwd change.

**Comment by ayushmanchhabra** [comment]
@breavyn I understand now, please go ahead with the pull request. 

> Keeping in mind changing this behaviour would break scripts relying on the cwd change.

I think as long as the application builds correctly in managed manifest mode, it should be fine.
