### ISSUE TITLE
Integrity check fails on community ffmpeg binary

### ISSUE THREAD

**Issue by zkrige** [nwutils/nw-builder#1209]
4.9.0

Error: SHA256 checksums do not match.
    at verify (file:///Users/distiller/desktop_viewer/mac/node_modules/nw-builder/src/get/verify.js:42:15)
    at get (file:///Users/distiller/desktop_viewer/mac/node_modules/nw-builder/src/get/index.js:137:5)
    at Module.nwbuild (file:///Users/distiller/desktop_viewer/mac/node_modules/nw-builder/src/index.js:86:5)

Fatal error: SHA256 checksums do not match.

**Comment by ayushmanchhabra** [comment]
Does this happen every time or once in a while?

**Comment by zkrige** [comment]
It happens on every build. If I roll back to 4.8.1 it works fine

**Comment by ayushmanchhabra** [comment]
Will try to debug this over the weekend. I know that the shasum is generated properly, maybe its comparing the wrong file's shasums?

**Comment by ayushmanchhabra** [comment]
> It happens on every build. If I roll back to 4.8.1 it works fine

What options are you using for nwbuild?

**Comment by zkrige** [comment]
` "nwbuild": {
    "version": "0.91.0",
    "cache": true,
    "logLevel": "debug",
    "cacheDir": "./build/output/nwjs-cache",
    "srcDir": "./build/output/result",
    "ffmpeg": true,
    "glob": false
  }`

**Comment by ayushmanchhabra** [comment]
Could you try v4.8.10? I've improved the error message.

**Comment by ayushmanchhabra** [comment]
Also v4.10.0 has the rename helper apps functionality - let me know if any other osx bundles should be updated

**Comment by ayushmanchhabra** [comment]
Figured out the issue - it is comparing the checksum of the official ffmpeg with the generated checksum of the community ffmpeg.

**Comment by zkrige** [comment]
Excellent. I'll test the new version asap

**Comment by zkrige** [comment]
This still fails if you're using cache.

If I have previously downloaded ffmpeg, then the verify fails because ffmpeg hash is wrong

```
{"version":"0.92.0","cache":true,"logLevel":"debug","cacheDir":"./build/output/nwjs-cache","srcDir":"./build/output/result","ffmpeg":true,"glob":false,"mode":"get","flavor":"sdk","platform":"osx","arch":"arm64"}
Error: SHA256 checksums do not match. The file nwjs-v0.92.0-osx-arm64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/129.0.6668.59/libffmpeg.dylib expected shasum is bd45e411a355c0345b8655bd0b8d1f28d2cfd15f9dd425715c8702a04e69ca8e but the actual shasum is f697041a8ca371914f30113c62049d59ab4116d66d55960cd73a1fa30d93945b.
    at verify (file:///node_modules/nw-builder/src/get/verify.js:41:15)
    at get (file:///nw-builder/src/get/index.js:96:3)
    at Module.nwbuild (file:///nw-builder/src/index.js:84:5)

```

**Comment by zkrige** [comment]
Thanks! it looks like its working now

**Comment by ayushmanchhabra** [comment]
Does it output the warning message?

**Comment by zkrige** [comment]
yes it does
