### ISSUE TITLE
New mac-specific option needed: `NSLocalNetworkUsageDescription`

### ISSUE THREAD

**Issue by beaugunderson** [nwutils/nw-builder#1235]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Other

### Current/Missing Behaviour

macOS 15 now requires `NSLocalNetworkUsageDescription` in the `Info.plist` to enable local networking, so we need to be able to specify it.

### Expected/Proposed Behaviour

When passed to `app` for a macOS build, the `NSLocalNetworkUsageDescription` key is added to `Info.plist` like the other keys.

### Additional Info

- Package version: latest
- Operating System: macOS 15
- Node version: latest
- NW.js version: latest
- ...

**Comment by ayushmanchhabra** [comment]
https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription
@beaugunderson Looks like it is supported since MacOS 11. Are you open to creating a pull request?

**Comment by beaugunderson** [comment]
There's a FAQ here as well: https://developer.apple.com/forums/thread/663858

**Comment by beaugunderson** [comment]
Very open! I'll do that now. :)

**Comment by beaugunderson** [comment]
Done!
