### ISSUE TITLE
Don't discard information previously set by user when some nwbuilder manifest is found

### ISSUE THREAD

**Issue by Black-Platypus** [nwutils/nw-builder#1261]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Other

### Current/Missing Behaviour
User passes in an options Object for a project that has a "nwbuild" object in its package/manifest JSON.
All of the previously entered information is discarded, regardless of what's inside the `nwbuild` object
### Expected/Proposed Behaviour
Keys previously explicitly specified in the options object when calling `nwbuilder.bld` remain when they're not overwritten by any manifest encountered
### Additional Info

- Package version: 4.11.3
- Operating System: Windows 10 x64
- Node version: v20.9.0, 22.7.0
- NW.js version: 0.92.0

**Comment by ayushmanchhabra** [comment]
Didn't read through this well enough earlier. Maybe this should be documented somewhere.
