### ISSUE TITLE
Provide calculated values (final paths, names, versions, etc) to user without building app

### ISSUE THREAD

**Issue by Black-Platypus** [nwutils/nw-builder#1264]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Other

### Current/Missing Behaviour
User has their values they pass to nwbuild, but no way of double-checking, changing or even seeing any value that nw-builder arrives at
### Expected/Proposed Behaviour
User has an alternate "prepare" mode, where they can pass in their options and receive the calculated state (after parsing and applying defaults and path resolutions), to be able to check for validity and/or make adjustments
Usage like:
```
nwbuild({
	mode: 'prepare'
	// ...
});
```

### Additional Info

- Package version: 4.11.3
- Operating System: Windows 10 x64
- Node version: v20.9.0, 22.7.0
- NW.js version: 0.92.0

**Comment by ayushmanchhabra** [comment]
https://github.com/nwutils/nw-builder/pull/1265#issuecomment-2488425920
