### ISSUE TITLE
Cant't build NW application, an error was thrown.

### ISSUE THREAD

**Issue by fgt1t5y** [nwutils/nw-builder#1293]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Other

![图片](https://github.com/user-attachments/assets/23d24fd8-4de2-4f0a-b55d-b2586a959e04)

### Current/Missing Behaviour

Cant't build NW application, an error was thrown. `fileVersion` and `fileDescription` properties also can not apply to executeable file.

### Expected/Proposed Behaviour

No any error was thrown, and `fileVersion` and `fileDescription` properties can apply to executeable file.

### Additional Info

Build script content:

```javascript
nwbuild({
  version: "0.91.0",
  mode: "build",
  srcDir: "./dist",
  glob: false,
  flavor: "normal",
  platform: "win",
  managedManifest: {
    name: "litepad",
    main: "index.html",
    window: {
      id: "litepad-gui",
      title: "LitePad",
      position: "center",
      height: 660,
      width: 1060,
      min_height: 600,
      min_width: 800,
      icon: "./appicon.png",
    },
  },
  app: {
    name: "LitePad",
    fileVersion: "0.0.1",
    fileDescription: "LitePad",
    productName: "LitePad",
    productVersion: "0.0.1",
  },
});
```

- Package version: 4.11.6
- Operating System: Windows 11 21H2
- Node version: 20.12.2
- NW.js version: 0.91
- Repro link: https://github.com/fgt1t5y/LitePad
- Full log: https://paste.mozilla.org/dKxLGBb6

**Comment by ayushmanchhabra** [comment]
Thanks for the bug report, will look into this soon

**Comment by ayushmanchhabra** [comment]
This broke in https://github.com/nwutils/nw-builder/commit/03a55b919a7e5dfcc1d9fa3f06baa327804d67c4 when switching from `rcedit` to `resedit`

**Comment by fgt1t5y** [comment]
> Editing Windows exe resources functionality broke in [03a55b9](https://github.com/nwutils/nw-builder/commit/03a55b919a7e5dfcc1d9fa3f06baa327804d67c4) when switching from `rcedit` to `resedit`

Oh, how to fix it?

**Comment by ayushmanchhabra** [comment]
Feel free to give this a shot, it'll take me some time to get to this issue

**Comment by fgt1t5y** [comment]
> Feel free to give this a shot, it'll take me some time to get to this issue

I seem to have found the problem, I will make a PullRequest.

**Comment by ayushmanchhabra** [comment]
https://github.com/nwutils/nw-builder/blob/89f7d64a8c62feef69b6ddaef00a5b1d8aef6f16/src/util.js#L415
I think we need to validate all `options.app.*` parameters
