### ISSUE TITLE
Update executable file permissions from 700 to 755

### ISSUE THREAD

**Issue by NilsEnevoldsen** [nwutils/nw-builder#289]
Possible dupe of #268 and/or #269.

Originally reported as https://github.com/bastimeyer/livestreamer-twitch-gui/issues/210.

---

Replication:
1. Install app as user Alice
2. Try to run app as user Bob
3. Receive error about PowerPC applications not being supported

The issue appears to be permissions on the executable files:
- `/Applications/Livestreamer Twitch GUI.app/Contents/MacOS/nwjs`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Framework.framework/nwjs Framework`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper EH.app/Contents/MacOS/nwjs Helper EH`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper NP.app/Contents/MacOS/nwjs Helper NP`

Running `sudo chmod a+rx [file]` on these files fixes the issue.

**Comment by donkonstante** [comment]
tried changing the permissions and it allows me to open the app but it crashes

**Comment by NilsEnevoldsen** [comment]
It crashes when you open it? I can't replicate that. It works normally for me after these steps.

**Comment by donkonstante** [comment]
seems it wasn't working due to the 0.13 beta version. 

In version 0.12.3 works

**Comment by adam-lynch** [comment]
Is this only on OS X? A pull-request would be fantastic if you could :smile:

**Comment by NilsEnevoldsen** [comment]
Actually, the more I look at this the more I think that this issue belongs with nw.js, as @bastimeyer mentioned. Do you see any reason why the prebuilt nw.js OSX binary executables should not be 755?

**Comment by adam-lynch** [comment]
@NilsEnevoldsen no I don't sorry

**Comment by adam-lynch** [comment]
I guess we can close this for now then. I'll reopen if you think it's not NW.js

**Comment by bastimeyer** [comment]
True, the NW.js archive should have the proper file permissions set.
However, the builder could do this too. I had an issue just recently after I moved my repo (with the cached NW.js files) to another partition on my system and the executable permission was lost.
If we know which files are `u+x`, setting those to `+x` should be fairly easy in the build process.

**Comment by adam-lynch** [comment]
Sure, I don't mind. I've reopened this. I'm crazy busy at the moment. A PR would be great :D

**Comment by bastimeyer** [comment]
The linux archives are now also affected by this (don't know when this started, but I'm experiencing this while using 0.19.0). All files either have the permission 600 or 700.

This results in the following error when trying to run the application from another user:
```
error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
```
(the shared libs in the lib subfolder don't have read permissions)

Running
`chmod -R g+r,o+r /path/to/app-folder`
after building the application with nw-builder fixes the issue.
