### ISSUE TITLE
App file on mac is very large

### ISSUE THREAD

**Issue by mfehrenb** [nwutils/nw-builder#457]
Hello,

I'm trying to upgrade to the latest nwjs stable build to repair a crash issue in our application. When switching to 0.23.5 the created app file is about 600MB which is three times larger than when using 0.18.1.

My buildMac.js file is as follows:

var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
appName: 'OpenText Core',
  files: './source/**/*', // use the glob format
  buildDir: './build',
  platforms: ['osx64'],
  version: '0.23.5',
  macIcns: './builds/mac_files/app.icns',
  zip: false });

nw.on('log',  console.log);

// Build returns a promise
nw.build()
  .then(function () {
    console.log('Done building the nwjs app');
  }).catch(function (error) {
    console.error(error);
  });

This is run using our custom python file and using node:
node_nw_builder_result = os.system("node buildMac.js")

When opening up the created app file it looks like the nwjs framework is about 538MB. When I download the sdk version directly it's about 260MB. Seems like there is a problem in how this is being built. The windows output is almost identical in size.

Any insight here would be greatly appreciated.

**Comment by mfehrenb** [comment]
I should note the version of nw-builder I'm using is ^3.4.1

**Comment by Arti3DPlayer** [comment]
@mfehrenb remove your node_modules folder

**Comment by adam-lynch** [comment]
Hmm sorry to hear that. Is there any chance you could supply an example project?

**Comment by Blatman** [comment]
This issue may be dead - I had a look at the Twine app folder structure at the time and the nwjs Framework.framework bundle folders were not symlinked.
The symlinking change happened upstream at nwjs 0.22.0 and NWB was updated afterwards. I think this was a combination of updated nw.js and pre-updated nw-builder being used for the twine builds.
Note: Twine.app seems to have migrated from nwjs to electron now.

<img width="1237" alt="twinestructure" src="https://user-images.githubusercontent.com/11089335/50281583-d5f05f80-0447-11e9-8eca-4a5bab8ce73b.png">

Cheers

**Comment by ayushmxn** [comment]
If this issue still persists, I can reopen this.
