### ISSUE TITLE
Linux ARM support

### ISSUE THREAD

**Issue by AndrejaN** [nwutils/nw-builder#494]
Hi guys,

this is not an issue, but i don' know where to write on GitHub for such request.
Could you be kind and add linux ARM support for nw-builder package? I'm using this package for my PopcornTime ARM version. After running _npm install_ and downloading the needed node_modules i manually copy these files [ARMFiles.zip](https://github.com/nwjs-community/nw-builder/files/2152203/1.zip) in nw-builder/lib, which they actually overwrite these files in the **lib folder**:

detectCurrentPlatform.js
index.js
platforms.js

After this i run: _gulp build -p linuxarm_
**CAUTION**: Because i don't know how to detect ARM platform in file detectCurrentPlatform.js i removed linux32 support and instead of that platform a placed linuxarm. In real working file, it should be add probably another line for ARM architecture CPUs.

Because i don't want to mess with your source files in the code without your permissions, could it be possible in the next version of the package to add ARM support?

Thanks in advance

**Comment by kessler** [comment]
@AndrejaN Could you submit a quick PR (nothing production ready) so I can have a look?

**Comment by AndrejaN** [comment]
Hi, sorry for my later answer. Maybe my solution is not the most elegant, but works for my PopcornTime distribution under Rpi3 by following this lines of code:

"After running _npm install_ and downloading the needed node_modules i manually copy these files ARMFiles.zip in the ../node-modules/nw-builder/lib, which they actually overwrite these files in the **lib** folder: 

detectCurrentPlatform.js
index.js
platforms.js

Then i copy in ../cache folder these files from https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/download/v0.28.4/nwjs-sdk-v0.28.4-linux-arm-chrome-branding.tar.gz
**After this i run: gulp build -p linuxarm" and wolla!! Copy and run in Raspi3 the output of command**

Here are the 3 files in zip archive.>>>> [Adding_LinuxARM.zip](https://github.com/nwjs-community/nw-builder/files/2707569/Adding_LinuxARM.zip)
I think that in Line88 in Index.js 'linuxarm' should be added, but it works in my case without.

**Comment by kessler** [comment]
@AndrejaN thank you very much for your response. However, I can't really work with something that is not a PR. If you want to introduce these changes to nw-builder it has to start with a PR.

**Comment by AndrejaN** [comment]
I'm sorry, i'm new on github and i have never made PR, or mess in the repository code.
As i read on Google, i should open a pull request and add the code there, right?
I'll do that.

Sorry for my ignorance.

**Comment by kessler** [comment]
@AndrejaN nothing to apologize for. It's all good. Take a look at this: https://help.github.com/articles/creating-a-pull-request/

**Comment by matt-cook** [comment]
I've created a PR for this: https://github.com/nwjs-community/nw-builder/pull/522

Hoping to get to testing it sometime soon. Let me know if you see any issues.

**Comment by AndrejaN** [comment]
Hi,

i have just tested by downloading the provided files and putting them into the folder. 
It works just fine, the PT is built without a problem for my RaspberyPi3. Thank you very much.
When could i expect to be included in the final version?

Andreja

**Comment by ayushmxn** [comment]
https://github.com/LeonardLaszlo/nw.js-armv7-binaries
This looks promising

**Comment by tharatau** [comment]
For Linux arm builds, we would need to create a custom manifest file and use https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases/ as the downloadUrl

**Comment by tharatau** [comment]
Closing for now.

**Comment by ayushmanchhabra** [comment]
See https://github.com/nwutils/nw-builder/commit/9a92688d848a83a8317196c254009a6c1eeffa44
