### ISSUE TITLE
zipping issues

### ISSUE THREAD

**Issue by indexofrefraction** [nwutils/nw-builder#512]
hi,

first, i would suggest  an option zipVerbose or something
to allow suppressing that zipping spills the terminal by logging each single file

then second i don't understand why there is a warning when using macZip:
"macZip is deprecated. Use the zip option instead."

the documentation says zip is only for windows.
so if i want to zip on macos i have to use macZip, so how can it be deprecated?

for me it would be more logical if zip would affect all systems,
with macZip, winZip, linuxZip acting as optional overrides.

best, index

**Comment by Blatman** [comment]
The --quiet option set to true should kill the "zipping file" logs - the def is false so it will be verbose.

The macZip deprecation is confusing - I think the intention a while ago was to remove it as it is normal to have the app.nw folder in the OSX package unzipped.

 In my version of NWB I have retained the macZip and made the default false. I looked at the code and found that if macZip was not set then if a simultaneous OSX/Win build was done and the win zip was true then the OSX build would also be zipped - this does not occur if macZip is set to false.
My view is similar to yours in that I am happy to retain macZip as an option but I just make sure it is always false.

Cheers.
