### ISSUE TITLE
Install Stops after some packages fetching

### ISSUE THREAD

**Issue by Dev1lroot** [nwutils/nw-builder#521]
npm i nw-builder -g --verbose

npm info it worked if it ends with ok
npm verb cli [ 'I:\\WindowsLibrary\\Terminal\\nodejs\\node.exe',
npm verb cli   'I:\\WindowsLibrary\\Terminal\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   'nw-builder',
npm verb cli   '-g',
npm verb cli   '--verbose' ]
npm info using npm@6.11.3
npm info using node@v10.16.3
npm verb npm-session c4e537fdfa5df4b8
npm http fetch GET 200 https://registry.npmjs.org/nw-builder 241ms
npm timing stage:loadCurrentTree Completed in 348ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
npm http fetch GET 200 https://registry.npmjs.org/boxen 444ms
npm http fetch GET 200 https://registry.npmjs.org/lazy-req 577ms
npm http fetch GET 200 https://registry.npmjs.org/extract-zip 599ms
npm http fetch GET 200 https://registry.npmjs.org/deprecate 606ms
npm http fetch GET 304 https://registry.npmjs.org/graceful-ncp 624ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 628ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/graceful-fs-extra 633ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/boxen/-/boxen-1.3.0.tgz 198ms
npm http fetch GET 304 https://registry.npmjs.org/archiver 683ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chalk 704ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash 709ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/lazy-req/-/lazy-req-2.0.0.tgz 203ms
npm http fetch GET 200 https://registry.npmjs.org/deprecate/-/deprecate-1.0.0.tgz 202ms
npm http fetch GET 200 https://registry.npmjs.org/archiver/-/archiver-2.1.1.tgz 158ms
npm http fetch GET 304 https://registry.npmjs.org/optimist 259ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/plist 526ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rcedit 506ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/progress 513ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/request 515ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 500ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-glob 635ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 659ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 631ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/thenify 289ms
npm http fetch GET 304 https://registry.npmjs.org/winresourcer 273ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/update-notifier 304ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/recursive-readdir-sync 914ms

/* 
And nothing more, it's been frozen like that for an hour, another attempts caused installation to be frozen on other packages, but this is definitely not a problem with Node or NPM, because other packages installing normally
*/

**Comment by djmisterjon** [comment]
https://github.com/nwjs-community/nw-builder/issues/530#issuecomment-778778367

**Comment by ayushmxn** [comment]
If this is due to the zip files in the `test` directory, I could just not include them in the next release.

**Comment by ayushmxn** [comment]
This is turning out to be trickier than I thought. If someone is having this issue, I can bump up it's priority and get started on this otherwise I'm going to leave this for later.

**Comment by ayushmxn** [comment]
Fixed by #583
