### ISSUE TITLE
.env file not included when using nwbuild in CLI

### ISSUE THREAD

**Issue by ttemple06** [nwutils/nw-builder#525]
This issue is similar to https://github.com/nwjs-community/nw-builder/issues/491 but I'm using the CLI. I have an .env file in the /src directory and expect it to be included with the other files, but when I try to run `nwbuild --platforms win64 --buildDir dist/ src/`, it is not including the src/.env file. I have tried globbing syntax but same result. I am unable to find a solution. What am I missing?

**Comment by ayushmxn** [comment]
As mentioned in #491, you'll have to pass a custom glob pattern for dot files. From v3.8.2, you can pass multiple file paths in the CLI. For example: `nwbuild ./src ./**/.*` Ping me here if this is still an issues.
