### ISSUE TITLE
Any chance to disable the packing/bundling/zipping?

### ISSUE THREAD

**Issue by Geddo** [nwutils/nw-builder#539]
I switched from electron to nw because the performance is def. better for windows apps. Sadly I couldnt find any option to disable the packaging of the resources. In electron there is an option `asar: false` to prevent that.

Example:
nwbuild --platforms win64 --buildDir nwtest/ www/

Result:
All files from www/ are getting packed in one myapp.exe

Question:
Is there any option for nwbuild to keep the source-files as they are, in a subfolder of the app to change assets after building?

**Comment by Blatman** [comment]
Options.zip set to false (--zip false) should produce a discrete nw folder in the windows file bundle.

**Comment by Geddo** [comment]
Thanks for the reply @Blatman but sadly that doesnt work. It's still zipping stuff together and doesnt create that separated asset folder. Tried the zip: false in my package.json AND in my script command via `wbuild --platforms win64 --zip false --buildDir nwtest/ www/`

I'm on nwbuilder 3.5.7 and nw 0.54.1

**Comment by Blatman** [comment]
Ah OK - probably still faulty in the latest version.
If you wish you can download a modified copy of this distro which has a lot of fixes but should work OK in CLI mode.
https://www.wanderinghippo.org.uk/bin/nwjs/nwbcli-blatmod.zip

Check bug #458 which I think related to this - the nwbuild file is in the bin folder of the zip and can be opened with a text editor. I haven't spent much time on the CLI version lately since I'm down other rabbit holes but I'm pretty certain that it was OK for discrete app folders.

**Comment by ayushmxn** [comment]
After taking a quick look, I noticed that the zip option is not included in the [CLI script](https://github.com/nwutils/nw-builder/blob/master/bin/nwbuild). Seems like an easy fix which I'll probably get to by tomorrow or day after.

**Comment by Geddo** [comment]
@ayushmxn sorry to bug you again - it still doesnt work in my case (windows with git bash). did a simple console.log(argv.zip) in bin/nwbuild.cjs which returns false correctly but somehow it's still zipping everything.
When I hardcode "zip: false", in bin/nwbuild.cjs in Line:81 it works 🤪

**Comment by ayushmxn** [comment]
@Geddo I'll look into this!

**Comment by ayushmxn** [comment]
I'm gonna try and give this a ahot today. The code for zipping is pretty mangled.

**Comment by ayushmxn** [comment]
@Geddo try setting `mergeZip` to `false`

**Comment by ayushmxn** [comment]
Just tested and it still merges if `mergeZip` is `false`.

**Comment by ayushmxn** [comment]
Resolved by #661
