### ISSUE TITLE
nw-builder depends on request which is deprecated

### ISSUE THREAD

**Issue by jssuttles** [nwutils/nw-builder#545]
The request package is deprecated.
https://github.com/request/request/issues/3142

Replacing this deprecated package will get rid of this dependabot issue: https://github.com/advisories/GHSA-896r-f27r-55mw

**Comment by ayushmxn** [comment]
@jssuttles I'll get to this eventually but currently focusing on fixing bugs. Feel free to submit a PR in the meantime!

**Comment by ayushmxn** [comment]
Lock file has json-schema v0.4.0. I'll eventually remove `request` package usage. Closing in favour of #623.

**Comment by ayushmxn** [comment]
Resolved by #661
