### ISSUE TITLE
MacOS ARM support

### ISSUE THREAD

**Issue by ghost** [nwutils/nw-builder#546]
Would it be possible to create native builds for Mac on ARM?

Related to https://github.com/nwjs/nw.js/issues/7620#issuecomment-957794983 and https://github.com/nwjs-community/nw-builder/pull/522

**Comment by berard** [comment]
FYI it is currently working in my fork: https://github.com/nwjs-community/nw-builder/pull/547

**Comment by ayushmxn** [comment]
https://github.com/nwutils/nw-builder/pull/584#issuecomment-1171253606

**Comment by tharatau** [comment]
For MacOS arm64 builds, we would need to create:
- a manifest file
- TBD

**Comment by zkrige** [comment]
Hmmm... arm64 doesn't run on my Mac. it just dumps back to shell
