### ISSUE TITLE
v4.0

### ISSUE THREAD

**Issue by ayushmxn** [nwutils/nw-builder#556]
# RFC

Most of the code is based on the assumption that you download from `dl.nwjs.io`. The goal right now is to allow people to override the `downloadUrl` and `manifestUrl` and have another argument for defining some rules on how to parse the manifestUrl. The rules for `dl.nwjs.io` is in `Platforms.js`.

## Module

```javascript
// ESM
import { nwbuild } from "nw-builder";
// CJS
const nwbuild = require("nw-builder");

nwbuild({
  srcDir: "./src",
  version: "0.68.2",
  flavor: "sdk",
  platform: "linux",
  arch: "x64",
  downloadUri: "https://dl.nwjs.io", //https or file sys
  manifestUri: "https://nwjs.io/versions.json", // https or file sys,
  mode: "build",
  outDir: "./out",
  // flags:
  zip: true,
  noCache: true,
  noGlob: true,
});
```

**Comment by TheJaredWilcurt** [comment]
`version: 0.64.1` is a syntax error, I assume it should be `version: '0.64.1'`.

**Comment by ayushmxn** [comment]
> `version: 0.64.1` is a syntax error, I assume it should be `version: '0.64.1'`.

Yup, fixed

**Comment by TheJaredWilcurt** [comment]
What is `options` in this example. It is provided by the `nw-builder` module, and then passed back in to it? Is it just an object of the default options used internally? Why pull it out, just to pass it back in? Ultimately, you'll still need to validate what inputs are passed in by the user, and default options not passed in. So why not handle that in the same step?

My process for library API's is usually:

1. Create a dummy object with all default options already set
1. Take in the user's object
1. Validate each part of the user's object is correct
1. If a user option is valid, then override the property on the dummy object
1. If it isn't valid, then use the default, and log helpful, human readable message explaining why their input was invalid (must be a number, must be an array of booleans, must be one of these 3 specific strings, etc)
1. Then carry on trying to perform the operation based on whatever properties are in the dummy object (if possible).

I usually just put all that in a `validation.js` file that always returns a valid options object, and have that be the first thing called. From that point on, all of my library code is free from safety checks and can safely assume that all values exist, are the correct type, and compatible with the logic in the library. It's a lot of extra work upfront, but it separates this validation step and the unit tests for it from the rest of the code. Often times this validation step ends up with more code than the rest of the actually library code, which just goes to show how much complexity there is involved with taking inputs from unknown sources. It's worked well for me on my libraries. Ultimately, the only way to be sure something will work in JavaScript, is to validate it at runtime.

**Example:**

* [library.js](https://github.com/nwutils/create-desktop-shortcuts/blob/main/src/library.js) = 308 lines
* [validation.js](https://github.com/nwutils/create-desktop-shortcuts/blob/main/src/validation.js) = 644 lines

**Comment by ayushmxn** [comment]
> What is `options` in this example.

The current design is a draft. I agree that there's no point in passing `options` in again. But before changing it I wanted to come up with something better. For example:

```javascript
const { run } = nwbuild(
  version = "0.64.1",
  flavor = "normal" // default value of "sdk"
  ...
);
```
Something like this with reasonable defaults. I like separating the validation and library logic approach - I've seen it in a few places and it's worked well.

**Comment by ayushmxn** [comment]
> It's a lot of extra work upfront, but it separates this validation step and the unit tests for it from the rest of the code.

Feeling that rn lol. It's definitely more work but worth the effort.

**Comment by ayushmxn** [comment]
Most of the code is based on the assumption that you download from dl.nwjs.io. How can we make the code independent of this?
