### ISSUE TITLE
Dependency Update Tracker

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwutils/nw-builder#558]
# There have been **[28](# '28')** breaking changes.

## Your project is **[305](# '305')** versions behind being completely up-to-date.

Status | Package | Version | Type | Latest | Behind by | Breaking
:-- | :-- | :-- | :-- | :-- | :-- | :--
&#128165; | [archiver](https://www.npmjs.com/package/archiver) | 2.1.1 | dependencies | 5.3.1 | 15 | 3
&#128165; | [boxen](https://www.npmjs.com/package/boxen) | 1.1.0 | dependencies | 6.2.1 | 21 | 5
&#128165; | [chalk](https://www.npmjs.com/package/chalk) | 2.3.2 | dependencies | 5.0.1 | 12 | 3
&#10004; | [deprecate](https://www.npmjs.com/package/deprecate) | 1.1.1 | dependencies | 1.1.1 | 0 | 0
&#128165; | [extract-zip](https://www.npmjs.com/package/extract-zip) | 1.6.5 | dependencies | 2.0.1 | 6 | 1
&#10004; | [graceful-fs-extra](https://www.npmjs.com/package/graceful-fs-extra) | 2.0.0 | dependencies | 2.0.0 | 0 | 0
&#10004; | [graceful-ncp](https://www.npmjs.com/package/graceful-ncp) | 3.0.0 | dependencies | 3.0.0 | 0 | 0
&#10004; | [inherits](https://www.npmjs.com/package/inherits) | 2.0.4 | dependencies | 2.0.4 | 0 | 0
&#128165; | [lazy-req](https://www.npmjs.com/package/lazy-req) | 2.0.0 | dependencies | 3.0.0 | 1 | 1
&#10004; | [lodash](https://www.npmjs.com/package/lodash) | 4.17.21 | dependencies | 4.17.21 | 0 | 0
&#10004; | [optimist](https://www.npmjs.com/package/optimist) | 0.6.1 | dependencies | 0.6.1 | 0 | 0
&#10004; | [plist](https://www.npmjs.com/package/plist) | 3.0.5 | dependencies | 3.0.5 | 0 | 0
&#10004; | [progress](https://www.npmjs.com/package/progress) | 2.0.3 | dependencies | 2.0.3 | 0 | 0
&#128165; | [rcedit](https://www.npmjs.com/package/rcedit) | 1.0.0 | dependencies | 3.0.1 | 10 | 2
&#10004; | [recursive-readdir-sync](https://www.npmjs.com/package/recursive-readdir-sync) | 1.0.6 | dependencies | 1.0.6 | 0 | 0
&#10004; | [request](https://www.npmjs.com/package/request) | 2.88.2 | dependencies | 2.88.2 | 0 | 0
&#128165; | [rimraf](https://www.npmjs.com/package/rimraf) | 2.5.2 | dependencies | 3.0.2 | 11 | 1
&#128165; | [semver](https://www.npmjs.com/package/semver) | 5.5.0 | dependencies | 7.3.7 | 28 | 2
&#10004; | [simple-glob](https://www.npmjs.com/package/simple-glob) | 0.2.0 | dependencies | 0.2.0 | 0 | 0
&#128165; | [tar-fs](https://www.npmjs.com/package/tar-fs) | 1.16.2 | dependencies | 2.1.1 | 5 | 1
&#10004; | [thenify](https://www.npmjs.com/package/thenify) | 3.3.1 | dependencies | 3.3.1 | 0 | 0
&#128165; | [update-notifier](https://www.npmjs.com/package/update-notifier) | 2.4.0 | dependencies | 5.1.0 | 11 | 3
&#10004; | [winresourcer](https://www.npmjs.com/package/winresourcer) | 0.9.0 | dependencies | 0.9.0 | 0 | 0
&#10004; | [decompress-zip](https://www.npmjs.com/package/decompress-zip) | 0.3.3 | devDependencies | 0.3.3 | 0 | 0
&#10004; | [eol](https://www.npmjs.com/package/eol) | 0.9.1 | devDependencies | 0.9.1 | 0 | 0
&#10004; | [eslint](https://www.npmjs.com/package/eslint) | 8.15.0 | devDependencies | 8.15.0 | 0 | 0
&#128165; | [nock](https://www.npmjs.com/package/nock) | 9.0.5 | devDependencies | 13.2.4 | 147 | 4
&#10004; | [prettier](https://www.npmjs.com/package/prettier) | 2.6.2 | devDependencies | 2.6.2 | 0 | 0
&#10004; | [redtape](https://www.npmjs.com/package/redtape) | 1.0.0 | devDependencies | 1.0.0 | 0 | 0
&#128165; | [tap-spec](https://www.npmjs.com/package/tap-spec) | 4.1.1 | devDependencies | 5.0.0 | 2 | 1
&#128165; | [tape](https://www.npmjs.com/package/tape) | 4.9.0 | devDependencies | 5.5.3 | 36 | 1

Auto-Generated with [DepChecker](https://github.com/TheJaredWilcurt/depchecker).

**Comment by ayushmxn** [comment]
Thanks! Updating dependencies is definitely one of the things on top of my list but keeping them as it is for now since it's possible that after I make my changes (see [dev-554](https://github.com/nwjs-community/nw-builder/tree/dev-554)), I won't even need some or most of them anymore.
