### ISSUE TITLE
[Known Bug] NW.js `v0.24.4` hangs on "Launching App"

### ISSUE THREAD

**Issue by gauryan** [nwutils/nw-builder#562]
[Bug] nwbuild module `v3.6.0` hangs at "Launching App" on Windows

---

### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [ ] Other

### Additional Info

- Operating System:
- Node version:
- NW.js version:
- ...

**Comment by gauryan** [comment]
I make [a example](https://github.com/gauryan/nw_test). 
we use NW.js v0.24.4 on Node v16.

**Comment by ayushmxn** [comment]
I was able to reproduce - seems like an issue with version v0.24.4. Is there anything stopping you from using the latest version (v0.64.1)?

**Comment by ayushmxn** [comment]
Renaming this and keeping this open for better visibility.
