### ISSUE TITLE
Is there an option to compile files into a V8 snapshot?

### ISSUE THREAD

**Issue by zdev-online** [nwutils/nw-builder#580]
### Issue Type

- [ ] Bug Fix
- [x] Feature
- [ ] Other

In the NW documentation.js has a section ["Protect JavaScript Source Code"](https://docs.nwjs.io/en/nw50/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/)
Is it possible to compile files into a V8 snapshot? And if there is, how to "enable\activate" it in nw-builder?

**Comment by ayushmxn** [comment]
I believe the `nwjc` command should create a v8 snapshot but I haven't tried this myself. Currently there is no way to create a snapshot via `nw-builder`.

**Comment by ayushmxn** [comment]
The `nwjc` is found under your the `/cache` folder.  You could potentially do `path/to/nwjc source.js binary.bin`. Closing this for now. Ping me here if you have any further questions!
