### ISSUE TITLE
Zipping best practice

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwutils/nw-builder#581]
**Current Docs/API:**
```
options.mergeZip

Type: Boolean Default value: true

WINDOWS AND LINUX ONLY: Merge the source file package with the Node Webkit executable.
```

This approach has come to be known as an anti-pattern, it should no longer be enabled by default or recommended in the new API.

This approach involves packaging your project code into a `.zip` then performing `copy /b nw.exe+package.zip app.exe` or `cat nw package.zip > app && chmod +x app`. Producing an executable with the zip file built-in to it.

When you double-click the executable, the first thing it does is extract the zip file contents to a temp folder, then launch the app from that location. This requires unzipping the project files on every launch, making the start up time for apps slow for no benefit.

A better approach is to store the project files in a `package.nw` folder and place the folder next to the `nw.exe`. So it just runs directly from the file system.

**Comment by ayushmxn** [comment]
Thanks! I haven't even reached here but this is definitely good to know before getting into zip functionality.

**Comment by TheJaredWilcurt** [comment]
If you put all your files in a `package.nw` folder next to `nw.exe` and then zip all of that together, that's fine, example:

* https://github.com/TheJaredWilcurt/WuhdAppusDat/releases/download/v2.0.0/LIN-64_WuhdAppusDat_2.0.0.zip

**Comment by TheJaredWilcurt** [comment]
You got it, you can download the example I linked above. but that's it:

* App.zip
  * nw files (nw.exe, ffmpeg, libEGL, icudtl, etc)
  * package.nw
    * all your files (package.json, index.html, etc)

**Comment by ayushmxn** [comment]
Closing this in favour of #623.
