### ISSUE TITLE
locales directory required to be copied for Win/Linux 0.10.* or over

### ISSUE THREAD

**Issue by nurishi** [nwutils/nw-builder#59]
node-webkit apps are now required to be shipped with locales folder for Windows and Linux 0.10.\* or over, otherwise 'navigator.language' becomes empty and fails to detect OS language.

Sorry, I have no time to create PR now but hope this information helps.
https://github.com/rogerwang/node-webkit/issues/2031

FYI, we have temporarily made a quick fix to add another Grunt task to copy locales dir but this can be done on node-webkit-builder side.

**Comment by senshu** [comment]
As far as I can see, #93 fixes the issue only for Windows. Linux is still affected.

**Comment by adam-lynch** [comment]
@senshu it would be great if you could create a PR
