### ISSUE TITLE
Verify SHA checksum for downloads

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwutils/nw-builder#593]
### Issue Type

- [ ] Bug Fix
- [x] Feature
- [ ] Other

### Expected/Proposed Behaviour

- Check if downloadUrl returns 200 OK
- Check if link to NW.js binary returns 200 OK
- Verify version
- Download binary
- Verify checksum
- If there is an error in any of the above steps, removing the partially downloaded binary

### Additional Info

This would be nice to have. If this is more of a priority for you, please consider making a pull request. Here are some helpful links:

https://github.com/nwjs/nw.js#verifying-binaries
https://github.com/openpgpjs/openpgpjs

- Operating System:
- Node version:
- NW.js version:
- Repro link:
- ...

**Comment by ayushmxn** [comment]
Closing this in favour of #623.

**Comment by ayushmanchhabra** [comment]
See https://github.com/nwutils/nw-builder/commit/9a92688d848a83a8317196c254009a6c1eeffa44
