### ISSUE TITLE
package.nw FILE_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by krazyjakee** [nwutils/nw-builder#594]
### Issue Type

- [x] Bug Fix
- [ ] Feature
- [ ] Other

### CurrentBehaviour
When trying to run the app with the following code:

```javascript
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
    files: './dist/**/**', // use the glob format
    platforms: ['win64'], // ['osx64', 'win32', 'win64', 'linux32', 'linux64'],
    version: 'latest',
    flavor: 'normal'
});

// Log stuff you want
nw.on('log',  console.log);

nw.run()
  .then(function () {
    console.log("all done!");
  })
  .catch(function (error) {
    console.error(error);
  });
```

error thrown:
```
Using cache for: win64
Launching App
App exited with code 0
```

Error in nwjs debug cache log: `cache\0.66.0-normal\win64\package.nw': FILE_ERROR_NOT_FOUND: The system cannot find the file specified. (0x2)`

### Expected/Proposed Behaviour

It should run the app

### Additional Info

- Operating System: Win11
- Node version: v16.14.2
- NW.js version: 0.66.0

**Comment by krazyjakee** [comment]
I don't understand the circle of debug hell I've been through the last 4 hours but the issue was that somewhere along the line I deleted the `main` field from the apps package.json

**Comment by ayushmxn** [comment]
Hey I just saw this. I must have accidently turned off my notifications! I'm working on writing some nice documentation - maybe this can help in the future:
http://nwutils.io/nw-builder/
