### ISSUE TITLE
Run the command `nwbuild --platforms ... --buildDir ... ./path/to/app` not work!

### ISSUE THREAD

**Issue by haiw2** [nwutils/nw-builder#606]
### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [x] Other

### Expected/Proposed Behaviour
I want to build the node webkit app by using the `nw-builder`, and i try the command `nwbuild  --platforms win64 --buildDir dist/ src/` , but doesn't work!
There are no any problems, errors, etc. I don't know how to solve that, could you help me?
### Additional Info

- Operating System: win64
- Node version: 6.14.10
- NW.js version: 0.66.1(-sdk)
- Repro link:
- ...

**Comment by ayushmxn** [comment]
I'll look into this today!

**Comment by ayushmxn** [comment]
Have you made sure that a `package.json` file is inside the `/src` directory?

**Comment by haiw2** [comment]
First, Need i make sure that a `package.json` file is inside the `/src` dir? Emm, isn't it inside the `project root directory`? 
Secondly, i had tried to set the `--mode build` , but the result was not changed.
Thirdly, sorry, i write the node version = 6 is wrong. In fact, `the 6 is npm version`, the node version is `v14.15.4`

**Comment by ayushmxn** [comment]
> First, Need i make sure that a package.json file is inside the /src dir? Emm, isn't it inside the project root directory?

Your `package.json` file can be anywhere as long as you pass it in the [`files` option](https://github.com/nwutils/nw-builder#optionsfiles-required). The CLI command could look like `nwbuild ./src/**/*.* ./package.json --platforms win64 --buildDir ./dist`

**Comment by ayushmxn** [comment]
@haiw2 any luck?

**Comment by ayushmxn** [comment]
@haiw2 Closing this for now. Ping me here if you have any issues.
