### ISSUE TITLE
Downloading NW.js fails due to `chmod` error on Windows 11

### ISSUE THREAD

**Issue by umurpza** [nwutils/nw-builder#607]
### Issue Type

- [x] Bug Fix
- [ ] Feature
- [ ] Other

### Current/Missing Behaviour
Downloading: https://dl.nwjs.io/v0.66.1/nwjs-sdk-v0.66.1-osx-x64.zip
  downloading [====================] 100% 0.0s
[19:27:18] '<anonymous>' errored after 38 s
[19:27:18] Error: ENOENT: no such file or directory, chmod 'D:\workspaces\web\APIP-Editor\cache\0.66.1-sdk\osx64\nwjs-sdk-v0.66.1-osx-x64\nwjs.app\Contents\Frameworks\nwjs Framework.framework\Resources'
    at Object.chmodSync (node:fs:1843:3)
    at D:\workspaces\web\APIP-Editor\node_modules\nw-builder\lib\downloader.cjs:134:16
    at Array.forEach (<anonymous>)
    at D:\workspaces\web\APIP-Editor\node_modules\nw-builder\lib\downloader.cjs:133:17
[19:27:18] 'build' errored after 38 s
node:events:505
      throw er; // Unhandled 'error' event
      ^

### NWB Usage
const nw = new NwBuilder({
    files: ['package.json', 'client/**/**', 'public/**/**', 'node_modules/'],

    version: '0.66.1',
    flavor: 'sdk',
    zip: true,
    platforms: ['win32', 'win64', 'osx64'],
    buildType: "versioned",
    buildDir: './builds/sdk/', // Where the build version is saved
    macIcns: './public/images/ae.icns'
});

gulp.task('build-dev', (done) => {
    nw.options.flavor = 'sdk';
    nw.options.buildDir = './builds/sdk/';
    (gulp.series('build')());
    done();
});

### Expected/Proposed Behaviour
No error

### Additional Info

- Operating System: Windows 11
- Node version:  16.15.0
- NW.js version: 0.66.1
- Repro link:
- ...

**Comment by ayushmxn** [comment]
To build NW.js applications need to define the `mode: 'build' option`. I realise that the docs are not too informative in this aspect.

**Comment by umurpza** [comment]
Here is the error I get after adding the mode property:

zachm@zachs-imac apip-editor % gulp build
/Users/zachm/Desktop/workspaces/web/apip-editor/node_modules/nw-builder/dist/index.cjs:1
var va=Object.create;var He=Object.defineProperty;var da=Object.getOwnPropertyDescriptor;var ga=Object.getOwnPropertyNames;var ma=Object.getPrototypeOf,Ea=Object.prototype.hasOwnProperty;var v=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports),ya=(e,t)=>{for(var r in t)He(e,r,{get:t[r],enumerable:!0})},$r=(e,t,r,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of ga(t))!Ea.call(e,i)&&i!==r&&He(e,i,{get:()=>t[i],enumerable:!(n=da(t,i))||n.enumerable});return e};var fe=(e,t,r)=>(r=e!=null?va(ma(e)):{},$r(t||!e||!e.__esModule?He(r,"default",{value:e,enumerable:!0}):r,e)),ba=e=>$r(He({},"__esModule",{value:!0}),e);var Ie=v((_f,Lr)=>{var _a="2.0.0",Oa=Number.MAX_SAFE_INTEGER||9007199254740991,Sa=16;Lr.exports={SEMVER_SPEC_VERSION:_a,MAX_LENGTH:256,MAX_SAFE_INTEGER:Oa,MAX_SAFE_COMPONENT_LENGTH:Sa}});var Ae=v((Of,Tr)=>{var Ia=typeof process=="object"&&process.env&&process.env.NODE_DEBUG&&/\bsemver\b/i.test(pr

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1071:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/zachm/Desktop/workspaces/web/apip-editor/node_modules/nw-builder/lib/index.cjs:22:5)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)

**Comment by ayushmxn** [comment]
I was able to build my app after a few tweaks. Let me spin up a repro real quick.

**Comment by umurpza** [comment]
I get the same error with your repro. I think it is due to Gulp CLI version 2.3.0

PS C:\Users\zachm\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607> gulp build-dev
[17:54:17] Using gulpfile ~\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607\gulpfile.js
[17:54:17] Starting 'build-dev'...
[17:54:17] Finished 'build-dev' after 3.8 ms
  downloading [====================] 100% 0.0s
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, chmod 'C:\Users\zachm\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607\cache\0.66.1-sdk\osx64\nwjs-sdk-v0.66.1-osx-x64\nwjs.app\Contents\Frameworks\nwjs Framework.framework\Resources'
    at Object.chmodSync (node:fs:1843:3)
    at C:\Users\zachm\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607\node_modules\nw-builder\lib\downloader.cjs:134:16
    at Array.forEach (<anonymous>)
    at C:\Users\zachm\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607\node_modules\nw-builder\lib\downloader.cjs:133:17
Emitted 'error' event on Domain instance at:
    at emit (node:internal/process/promises:138:33)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  errno: -4058,
  syscall: 'chmod',
  code: 'ENOENT',
  path: 'C:\\Users\\zachm\\Downloads\\nw-repro-nw-builder-607\\nw-repro-nw-builder-607\\cache\\0.66.1-sdk\\osx64\\nwjs-sdk-v0.66.1-osx-x64\\nwjs.app\\Contents\\Frameworks\\nwjs Framework.framework\\Resources'
}
PS C:\Users\zachm\Downloads\nw-repro-nw-builder-607\nw-repro-nw-builder-607> gulp -v
CLI version: 2.3.0
Local version: 4.0.2

**Comment by umurpza** [comment]
@ayushmxn your simplified repro works until I add osx64 as a platform. Running on Windows 11.

**Comment by ayushmxn** [comment]
Could you try upgrading Node to `v16.16.0`?

**Comment by umurpza** [comment]
Same error, slightly different:

[ INFO ] Downloading: https://dl.nwjs.io/v0.67.0/nwjs-sdk-v0.67.0-osx-x64.zip
  downloading [====================] 100% 0.0s
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, chmod 'D:\workspaces\web\nw-repro\cache\0.67.0-sdk\osx64\nwjs-sdk-v0.67.0-osx-x64\nwjs.app\Contents\Frameworks\nwjs Framework.framework\Resources'
    at Object.chmodSync (node:fs:1843:3)
    at D:\workspaces\web\nw-repro\node_modules\nw-builder\lib\downloader.cjs:134:16
    at Array.forEach (<anonymous>)
    at D:\workspaces\web\nw-repro\node_modules\nw-builder\lib\downloader.cjs:133:17
Emitted 'error' event on Domain instance at:
    at emit (node:internal/process/promises:138:33)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  errno: -4058,
  syscall: 'chmod',
  code: 'ENOENT',
  path: 'D:\\workspaces\\web\\nw-repro\\cache\\0.67.0-sdk\\osx64\\nwjs-sdk-v0.67.0-osx-x64\\nwjs.app\\Contents\\Frameworks\\nwjs Framework.framework\\Resources'
}

**Comment by ayushmxn** [comment]
I'm currently running Ubuntu 22.04 using WSL (Windows 11). I'll try reproducing this on Windows and see what's up. I'll try to get back to you by tomorrow.

**Comment by ayushmxn** [comment]
This is probably not related to globbing but could you try appending `**/*.*` after `client`, `public` and `node_modules` for the `files` argument. There is no default globbing pattern if none is specified.

**Comment by ayushmxn** [comment]
I ran the repro on Windows 11 via GitHub Actions and it built fine. Try deleting your `node_modules` and `packaje.json` and `npm install` again.

**Comment by umurpza** [comment]
Tried is on your repro, same error. 
`[ INFO ] Create cache folder in D:\workspaces\web\nw-repro\cache\0.66.1-sdk
[ INFO ] Downloading: https://dl.nwjs.io/v0.66.1/nwjs-sdk-v0.66.1-osx-x64.zip
  downloading [====================] 100% 0.0s
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, chmod 'D:\workspaces\web\nw-repro\cache\0.66.1-sdk\osx64\nwjs-sdk-v0.66.1-osx-x64\nwjs.app\Contents\Frameworks\nwjs Framework.framework\Resources'
    at Object.chmodSync (node:fs:1843:3)
    at D:\workspaces\web\nw-repro\node_modules\nw-builder\lib\downloader.cjs:134:16
    at Array.forEach (<anonymous>)
    at D:\workspaces\web\nw-repro\node_modules\nw-builder\lib\downloader.cjs:133:17
Emitted 'error' event on Domain instance at:
    at emit (node:internal/process/promises:138:33)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  errno: -4058,
  syscall: 'chmod',
  code: 'ENOENT',
  path: 'D:\\workspaces\\web\\nw-repro\\cache\\0.66.1-sdk\\osx64\\nwjs-sdk-v0.66.1-osx-x64\\nwjs.app\\Contents\\Frameworks\\nwjs Framework.framework\\Resources'
}
`

**Comment by ayushmxn** [comment]
Try v3.8.2-beta.1 - just published it.

**Comment by umurpza** [comment]
Error:

`[ INFO ] Create cache folder in D:\workspaces\web\nw-repro\cache\0.66.1-sdk
[ INFO ] Downloading: https://dl.nwjs.io/v0.66.1/nwjs-sdk-v0.66.1-osx-x64.zip
  downloading [====================] 100% 0.0s
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EEXIST: file already exists, symlink 'Versions\Current\Resources' -> 'D:\workspaces\web\nw-repro\cache\0.66.1-sdk\osx64\nwjs-sdk-v0.66.1-osx-x64\nwjs.app\Contents\Frameworks\nwjs Framework.framework\Resources'
Emitted 'error' event on Domain instance at:
    at emit (node:internal/process/promises:138:33)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'Versions\\Current\\Resources',
  dest: 'D:\\workspaces\\web\\nw-repro\\cache\\0.66.1-sdk\\osx64\\nwjs-sdk-v0.66.1-osx-x64\\nwjs.app\\Contents\\Frameworks\\nwjs Framework.framework\\Resources'
}`

**Comment by ayushmxn** [comment]
@umurpza try running `nw-builder` `v3.8.5`? I just refactored the download function.

**Comment by ayushmxn** [comment]
Closing this for now. Ping me here if it still doesn't work.
