### ISSUE TITLE
No build is created after running nwbuild

### ISSUE THREAD

**Issue by TorbenTK** [nwutils/nw-builder#617]
### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [x] Other

### Current/Missing Behaviour

Possibly the same as issue #606.
When I run the `nwbuild` command, even with minimal parameters (`nwbuild src/`), 'nothing' happens.

I run my commands from the root of my project in `package.json`. My `src/` folder holds another `package.json` with the window information nw uses, and also has `build` folder with the `index.html`. 

`nw src/` works, starting a dev build.

When I run the `nwbuild` command, the output is... well, 'empty':
```yarn run v1.22.19
$ nwbuild --platforms win64 --buildDir dist/ src/ --mode build
{}
Done in 1.10s.
```

Nothing happens after. No `dist` folder appears with a built nw. This problems still occurs with minimal parameters (`nwbuild src/`)

I'm using the latest versions of both nw (0.67.0) and nw-builder (3.8.2), building using node 16.13.0. Also tried 16.16.0, same result. I haven't tried downgrading versions of nw and nw-builder yet.

Am I missing something? Is this intended behavior and is it saving the build somewhere I can't find?

### Additional Info

An unrelated thing (perhaps?), when running:

`nwbuild --platforms win64,win32 --buildDir dist/ src/ --mode build`

It throws an error:

```
$ nwbuild --platforms win64,win32 --buildDir dist/ src/ --mode build
{}
C:\Projects\Project\node_modules\nw-builder\lib\index.cjs:107
        throw new Error("Unknown platform " + platform);
        ^

Error: Unknown platform win64,win32
    at C:\Projects\Nonprop\node_modules\nw-builder\lib\index.cjs:107:15
    at Array.forEach (<anonymous>)
    at new NwBuilder (C:\Projects\Nonprop\node_modules\nw-builder\lib\index.cjs:105:28)
    at nwbuild (C:\Projects\Nonprop\node_modules\nw-builder\lib\index.cjs:1088:14)
    at Object.<anonymous> (C:\Projects\Nonprop\node_modules\nw-builder\bin\nwbuild.cjs:142:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

- Operating System:
- Node version: 16.13.0
- NW.js version: 0.67.0 (latest)

**Comment by TorbenTK** [comment]
Well, that was quick. I resolved it.

`nwbuild --platforms win64 --buildDir dist/* src/* --mode build`

Add `*` to your paths on Windows 10 (VSCode), otherwise no build path will be found.

**Comment by ayushmxn** [comment]
That's because `nw-builder` uses globbing to identify files and/or folders. Maybe I should add a default globbing pattern if none is specified.
