### ISSUE TITLE
Nwbuild silently halts after downloading SDK while building. Shows no error; builld is not created

### ISSUE THREAD

**Issue by NottLexa** [nwutils/nw-builder#621]
### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [X] Other

### Current/Missing Behaviour

Trying to build app with `nwbuild --platforms linux64 --buildDir dist/* src/* --mode build`.
After `nwbuild` is launched, it is creating cache folder and downloading SDK from https://dl.nwjs.io, then halts and leaves no trace of app building. `nwbuild` doesn't download SDK if it is already in cacheDir.
* NWJS SDK for selected platforms are put in cacheDir.

Output (from Webstorm):
```
> nwbuild --platforms linux64 --buildDir dist/* src/* --mode build

[ INFO ] Latest Version: v0.67.1
[ INFO ] Using v0.67.1 (sdk)
[ INFO ] Create cache folder in C:\Users\alesh\WebstormProjects\Casual-Playground\cache\0.67.1-sdk
[ INFO ] Downloading: https://dl.nwjs.io/v0.67.1/nwjs-sdk-v0.67.1-linux-x64.tar.gz
  downloading [====================] 100% 0.0s


Process finished with exit code 0
```

Output if SDK is already downloaded:
```
> nwbuild --platforms linux64 --buildDir dist/* src/* --mode build

[ INFO ] Latest Version: v0.67.1
[ INFO ] Using v0.67.1 (sdk)
[ INFO ] Create cache folder in C:\Users\alesh\WebstormProjects\Casual-Playground\cache\0.67.1-sdk
[ INFO ] Using cache for: linux64

Process finished with exit code 0
```

**buildDir (dist) stays empty.**

### Expected/Proposed Behaviour

NWJS app in buildDir (dist). Or at least any error message in output if it is an error.

### Additional Info

- Operating System: Windows 10 x64
- Node version: 16.15.0
- NW.js version: 0.66.1

UPD: if `src` has no `package.json`, it runs with even less information:
```
> nwbuild --platforms linux64 --buildDir dist/* src/* --mode build


Process finished with exit code 0
```

**Comment by ayushmxn** [comment]
The command worked for me when I removed the * after dist/. Your input directory should have a `package.json` in it's path otherwise `nwbuild` won't recognise it as a NW.js app. For example:

```shell
nwbuild ./src/* ./package.json --mode=build --buildDir=./dist --platforms=linux64
```

I am aware that logging is severely lacking right now and it is one of my top priorities.

**Comment by NottLexa** [comment]
@ayushmxn Thank you.
