### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by ayushmxn** [nwutils/nw-builder#623]
# API v4

```shell
nwbuild install --version=0.67.0 --flavour=sdk --outDir
```
Install one or more NW.js binaries.

```shell
nwbuild develop --manifestFile=./nw.develop.json
```
`nwbuild` automatically looks for the `nw.develop.json` manifest which defines options which are more suited for development.

```shell
nwbuild package --manifestFile=./nw.package.json
```
`nwbuild` automatically looks for the `nw.package.json` manifest which defines options which are more suited for packaging.

```shell
nwbuild installer --extention=dmg
```
An installer for the packaged applications.

**Comment by sysrage** [comment]
IMO, all of this would be nice but none of it should be part of `nw-builder`. Instead, start a project like the Vue CLI tools. `nwcli` or something, which has this functionality.

**Comment by TheJaredWilcurt** [comment]
I agree with @sysrage, separating CLI and docker stuff makes sense to me. It lets their repo(s) be more scoped to the specific problem it is trying to solve. And it keeps the `nw-builder` more focused and allows it to evolve to handle more edge cases needed by the community.

`nw-builder` should be focused on running locally on the current platform. Then if you want to set up GitHub Actions to run against Win, Lin, and OSX, and do 1 native build on each, that can work. Or if you want to just run your code on a single box using docker for the native builds, you could do that instead. But inside the docker container it would still just be using `nw-builder` normally.

But in general I like the idea of having some tooling that simplifies the process of using Docker and building each platform in their native environment, with their correct Node versions. That solves a lot of problems.

**Comment by ayushmxn** [comment]
I knew what I wanted to build but didn't know if I should add it to a pre-existing tool like `nw-builder` or build one from scratch.  This clears things up, thanks!

**Comment by ayushmxn** [comment]
Working on it here:
https://github.com/ayushmxn/nwbuild

**Comment by sysrage** [comment]
> Working on it here: https://github.com/ayushmxn/nwbuild

Awesome! Might I suggest a name change, since many/most of the features aren't actually related to a "build" process? 😉

**Comment by ayushmxn** [comment]
Sure! I made this a while ago and wasn't sure of it's purpose.

**Comment by ayushmxn** [comment]
Motivation for this was due to https://github.com/electron-userland/electron-builder and https://github.com/electron-userland/electron-forge. Essentially an all in one build tool.
