### ISSUE TITLE
Bundle only required node_modules into exe

### ISSUE THREAD

**Issue by Geddo** [nwutils/nw-builder#625]
Hey gang,
I need for e.g. 'express' in my app which is not availibe in this setup cause nwbuild per default ignores all my dependencies somehow.
my root /package.json contains this:

    "dependencies": {    
    "dgram": "^1.0.1",    
    "express": "^4.18.1",

my /www/package.json contains this:

     "node-remote": "http://localhost:8080",   
     "node-main": "server.js"

my server.js contains this:

    const  express = require('express')
    const  app = express()
    const  path = require('path');
    let  server = app.listen(8080);

So everything works when I either not bundle the exe (zip: false) OR when I deploy all node_modules within:

    var  NwBuilder = require('nw-builder');
    var  nw = new  NwBuilder({
    files: ['./www/**/**', './node_modules/**/**'],
    platforms: ['win64'],
    buildDir:  './dist',
    version:  '0.67.1',
    flavor:  'sdk',
    zip:  true
    });
Which doesnt make sense, right 🤪
Is there another way to include only the required node_modules?

**Comment by Geddo** [comment]
I just installed in the dependencies separatly in my /src/-Folder and copy them via gulp into my /www/folder - makes it much more easier and lighter.

**Comment by ayushmxn** [comment]
Currently, there's no straightforward way of doing this. You could bundle your code such that only the required dependencies are included. You could also glob the specific modules (for example `./node_modules/express/**/*`) which is kind of tedious. I'm open to suggestions on making this process better.

**Comment by ayushmxn** [comment]
@Geddo you could have a directory for the nw app with a package.json in it and install your nw specific dependencies there.
