### ISSUE TITLE
[Bug] Invalid package.json main entry

### ISSUE THREAD

**Issue by emanuilov** [nwutils/nw-builder#666]
### Current/Missing Behaviour
The main entry points to index.js, which is missing

Also, import can't be used outside a module, so the readme should state
const { nwbuild } = require('nw-builder');

instead of:
import { nwbuild } from "nw-builder";

Or even better make nwbuild the default export of nwbuild.js , so we can remove the deconstructing approach

- Operating System:
Windows 10
- Node version:
v16.18.0
- nw-builder version
4.0.0-rc.6

**Comment by ayushmxn** [comment]
Thanks for this, I'll make it a default export.
