### ISSUE TITLE
Match all options in API, CLI and `package.json`

### ISSUE THREAD

**Issue by stevenvachon** [nwutils/nw-builder#67]
So that we can just write up an npm script for building instead of using Grunt/Gulp or the programmatic API.

**Comment by shenzhuxi** [comment]
Why not make all options available in package.json?

**Comment by sanderboom** [comment]
+1 for all options in package.json and/or all options available as cli arguments. Situation right now is somewhat confusing.

**Comment by sanemat** [comment]
I want this feature :heart_eyes:

**Comment by adam-lynch** [comment]
I'd really appreciate it if someone could [make a pull-request](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) to add these please 😄

**Comment by stevenvachon** [comment]
Why use this over [electron](https://npmjs.com/electron)?
