### ISSUE TITLE
Failure if cache directory doesn't already exist

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#691]
https://github.com/nwutils/nw-builder/blob/16eb002f6bf95f9e57645ac305c17480910419c5/src/get/getReleaseInfo.js#L14

If the cache directory doesn't already exist, `nw-builder` fails. Instead, it should automatically create the cache directory if it doesn't already exist.

**Comment by tharatau** [comment]
Definite oversight on my part. Thanks for pointing it out!
