### ISSUE TITLE
`resolve()` is in the wrong event listener for `compress()`

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#692]
https://github.com/nwutils/nw-builder/blob/dfae36194ca123e863c1eae02c86e918b8254602/src/bld/compress.js#L21

For file streams, the`resolve()` should be in the `close` event listener, not `end`. The `end` event never fires, so this promise never resolves.

**Comment by tharatau** [comment]
Oh weird, compressing the zip files worked for me so I never checked to look if the promise resolved or not

**Comment by sysrage** [comment]
As mentioned in #696, you should also reject with the error message instead of "1". Put the `console.log()` further down the stack.
