### ISSUE TITLE
Using `fs.*Sync` in async functions 😢 

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#693]
### Issue Type

- [X] Bug Fix
- [ ] Feature
- [ ] Other

### Current/Missing Behaviour

I haven't reviewed the entire codebase, but I just noticed `packager()` is using `fs.rmSync()`, `fs.cpSync()`, and `fs.readFileSync()` inside an async function: https://github.com/nwutils/nw-builder/blob/main/src/bld/package.js#L9

### Expected/Proposed Behaviour

`node:fs/promises` should be used in ESM modules (and async functions in general): https://nodejs.org/dist/latest/docs/api/fs.html#promises-api

**Comment by tharatau** [comment]
Yup, I'm aware. I've made those changes on #690

**Comment by sysrage** [comment]
Doh! Sorry for reporting before checking your PR. Was too busy trying to implement this with `nw-react`!

**Comment by tharatau** [comment]
All good!
