### ISSUE TITLE
Add configuration property to rename NW.js executable

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#695]
### Issue Type

- [ ] Bug Fix
- [X] Feature
- [ ] Other

### Current/Missing Behaviour

Please add a property to the `nwbuild` configuration object which allows users to specify a name that `nw.exe` (and the matching binary for all other operating systems) should be renamed as.

**Comment by tharatau** [comment]
I'm tackling this platform by platform, next PR will be for Windows config using `rcedit`

**Comment by sysrage** [comment]
Unlinked the PR, so this remains open. The PR is a good stop-gap, renaming the the name specified as `name` in `package.json`. Users still need a way to choose what name to use, though.
