### ISSUE TITLE
Linux builds fail if `nwbuild.linuxCfg` is not set

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#699]
### Issue Type

- [X] Bug Fix
- [ ] Feature
- [ ] Other

### Current/Missing Behaviour

Optional chaining isn't being used, which causes a failure if `nwbuild.linuxCfg` is not defined:
```
file:///C:/Users/Brian/Documents/Code/nw-react/node_modules/nw-builder/src/bld/linuxCfg.js:20
  if (typeof pkg.nwbuild.linuxCfg === "object") {
                         ^
```

### Expected/Proposed Behaviour

Use optional chaining:
```js
if (typeof pkg.nwbuild?.linuxCfg === "object") {
```

**Comment by tharatau** [comment]
Wow I literally remember doing that, must have made a typo

**Comment by sysrage** [comment]
So, it's actually even worse than just the missing optional chaining. This fails if you don't have `nwbuild` defined in `package.json` at all. I'm running this by passing all configuration objects as a parameter, not via CLI. If you don't have an `nwbuild` property in `package.json`, you get the error above. If you have `nwbuild` (even if it's an empty object), you still get the error above unless you have a `linuxCfg` prop or add the optional chaining fix.

Please fix this so you don't need `nwbuild` in `package.json` at all. The `linuxCfg` property should be optional, whether you're using `package.json` or passing a configuration object as a parameter to `nwbuild()`.

**Comment by tharatau** [comment]
> Edit: Second half of this is that you need to allow specifying linuxCfg as part of the configuration object passed to nwbuild(). As a workaround to the above issue, I tried adding this property but it didn't work.

`linuxCfg` as a nwbuild option definitely makes more sense.
