### ISSUE TITLE
Migration Guide v3->v4

### ISSUE THREAD

**Issue by tharatau** [nwutils/nw-builder#722]
### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [x] Other

### Current/Missing Behaviour

No migration guide to upgrade from v3 to v4.

### Expected/Proposed Behaviour

Should have migration guide to upgrade from v3 to v4.

### Additional Info

There's no point in having a migration guide unless the new version works. Blocked by #699, #704, #705, 706, #714, #715, #716

- Operating System: N/A
- Node version: N/A
- NW.js version: N/A
- Repro link: N/A

**Comment by andrericardo** [comment]
Is there a migration guide from v3 to v4?

https://github.com/nwutils/nw-builder/compare/v3.8.10...v4.0.0

**Comment by ayushmanchhabra** [comment]
https://github.com/nwutils/nw-builder/tree/v3?tab=readme-ov-file#migration-guide-v3---v4
@andrericardo Here it is. It may help partially with the migration process since v3 support hss been dropped and work on this guide has stopped.
