### ISSUE TITLE
Readme should include mode parameter

### ISSUE THREAD

**Issue by 64jcl** [nwutils/nw-builder#743]
### Issue Type

- [ ] Bug Fix
- [ ] Feature
- [x] Other

### Current/Missing Behaviour
Missing description of the all important --mode parameter.

### Expected/Proposed Behaviour
While the readme details the parameters it fails to generate a build for the given platforms unless you add --mode build
It defaults to just run your program in nwjs

**Comment by sysrage** [comment]
I agree this should be documented, but the default should also be changed to "build" not "run".

**Comment by tharatau** [comment]
Should the info be moved to the README or should a link be added pointing to the docs `https://nwutils.io/nw-builder/`?

**Comment by BrianBothwell** [comment]
> Should the info be moved to the README or should a link be added pointing to the docs `https://nwutils.io/nw-builder/`?

It's short enough that it makes sense to just include all of it in the README.

**Comment by sysrage** [comment]
> Should the info be moved to the README or should a link be added pointing to the docs `https://nwutils.io/nw-builder/`?

In my opinion, the documentation is short enough that it should all be included in the README.
