### ISSUE TITLE
"Could not find a package.json in your src folder".

### ISSUE THREAD

**Issue by aliaafreen** [nwutils/nw-builder#746]
while  creating build for windows for nwjs it gives the following error-

==============================================
 nwbuild --platforms win32 --win-ico fs.ico --buildDir build/ src/

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Could not find a package.json in your src folder".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

nwbuilder - 3.5.7
nw -0.71.1
node - 16.13.1

**Comment by tharatau** [comment]
Have you tried v3.8.6? Also please provide steps to reproduce (for eg: folder structure  code snippets).

**Comment by tharatau** [comment]
v4.0.3 is the current stable version so I'm closing this.
