### ISSUE TITLE
code: 'ERR_UNHANDLED_REJECTION'

### ISSUE THREAD

**Issue by aliaafreen** [nwutils/nw-builder#747]
nwbuild --srcDir=./src --mode=build --version=1.0.0 --flavour=normal --platform=win --arch=x64 --outDir=./build

 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% | ETA: 0s | 22833/22833
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

nwbuilder -4.0.2
node - 16.13.1

**Comment by tharatau** [comment]
3.8.6 is the current stable version. I'll be making a PR today and plan to release 4.0.3 (the new latest stable version) by tomorrow.

**Comment by Chinooyoel** [comment]
I tried leaving the static version and it worked for me. package.json
`"nw-builder": "3.5.7"`


I also tried adding the wildcards and it worked for me ./app/**/*
`node_modules/.bin/nwbuild -p win32 -v 0.14.7 ./app/**/* --winIco app/images/flex-logo.ico`

**Comment by tharatau** [comment]
v4.0.4 should fix this. If it doesn't feel free to ping me here or open another issue. Please have a look at the updated docs - namely now file globing is required. I'm linking the docs of the globing dependency that is used.
https://github.com/isaacs/node-glob#glob-primer
