### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by temnoregg** [nwutils/nw-builder#75]
Can't run nwbuild

It returns env: node\r: No such file or directory with every execution

nwbuild -r .
env: node\r: No such file or directory

nwbuild -h
env: node\r: No such file or directory

**Comment by donaldpipowitch** [comment]
Please reopen this. It doesn't look like the pull request will be merged soon. Need a fix.

**Comment by dottodot** [comment]
Yes please reopen this as it has not been fixed and I cannot use it.

**Comment by yujiangshui** [comment]
Same problem here on Mac OS X 10.9.5.

**Comment by yujiangshui** [comment]
I find the solution. Open the nwbuild (if your install with `-g`, you will find it at `/usr/local/lib/node_modules/node-webkit-builder/bin`) by vim (use `sudo vim nwbuild`), then use `:set ff=unix`.

Try it. @dottodot @siuying @albinekb @azu

**Comment by fyddaben** [comment]
thanks ,解决了 @yujiangshui

**Comment by mingfly** [comment]
used mac os
brew install dos2unix 
sudo dos2unix  nwbuild

**Comment by vikbez** [comment]
:+1: same problem here

**Comment by DevManny** [comment]
you can use VIM to change break line DOS to UNIX
first:
$ sudo vim /usr/local/bin/nwbuild

then press 
`:set ff=unix`
`enter key`
`:x`
`enter key`

done!

**Comment by wikiziner** [comment]
`:set ff=unix` worked for me :+1:

**Comment by adam-lynch** [comment]
If anyone can create a pull-request to fix this, then please do. I already
merged one in the past but it obviously mustn't have worked

**Comment by stevenvachon** [comment]
Everyone has totally over-complicated this issue. The solution is way back in my [above comment](https://github.com/mllrsohn/node-webkit-builder/issues/75#issuecomment-54980138).

**Comment by stephan-nordnes-eriksen** [comment]
@stevenvachon Except that this did not work for me, and probably for some others as well. I had to scan the whole directory. This has probably got something to do with someone pushing to the repo without using the propper re-formatter supplied in windows git, or someone using an editor that uses wrong line breaks.

**Comment by jrode** [comment]
`:set ff=unix` mac :+1:

**Comment by alexmelyon** [comment]
Have some problem. I use network share on windows machine. Is it related to line endings?

**Comment by wesleytodd** [comment]
Is there any way to get this fixed in the actual main line branch?  I just ran into it after installing `0.13.0-alpha7sdk` on OSx.  The fix from @stevenvachon is the solution that worked for me.

**Comment by marlonfa** [comment]
Osx 10.11 doesn't work, any solution? Thanks

**Comment by fschwarzer** [comment]
When I run ```npm install -g iothub-explorer``` on Ubuntu 16.04, I get the same error. Also, the executable is called ```nodejs``` and not ```node``` here so we needed to create a symlink to make it work.
