### ISSUE TITLE
[ ERROR ] 2023-01-05T08:19:05.751Z Invalid array length

### ISSUE THREAD

**Issue by davedoesdev** [nwutils/nw-builder#753]
### Issue Type

- [x] Bug Fix
- [ ] Feature
- [ ] Other

### Current/Missing Behaviour

I'm getting 

```
[ ERROR ] 2023-01-05T08:19:05.751Z Invalid array length
```

with the following `push()` inside the loop when I have a large number of matched files:

https://github.com/nwutils/nw-builder/blob/af32f1095578ac35c2cabcc7186ef8b4986277cb/src/nwbuild.js#L97

_Originally posted by @davedoesdev in https://github.com/nwutils/nw-builder/pull/749#discussion_r1062211098_

### Expected/Proposed Behaviour

No error. Should the `push()` go outside the loop?

### Additional Info

- Operating System: All
- Node version: 18
- NW.js version: 0.71.1
- Repro link:

**Comment by sysrage** [comment]
Additionally, this seems to conflict:

You describe `srcDir` as: "Directory to hold NW app files unless or array of file glob patterns"

But then you do this:
https://github.com/nwutils/nw-builder/blob/af32f1095578ac35c2cabcc7186ef8b4986277cb/src/nwbuild.js#L89

If a user provides an array of glob patterns (like you document is allowed), it will fail.

**Comment by sysrage** [comment]
> the `srDir` format is a string of one of more glob patterns separated by a spaces. For eg: `srcDir: ./srx/**/* ./node_modules/**/*`.

Curious why? Whatever you decide is fine, just update the docs if you keep it this way. IMO, allowing an array of glob patterns would be better, but 🤷🏻.

**Comment by tharatau** [comment]
On releasing v4, I changed `files` (type string | Array<string>) to `srcDir` (type string) without globing. I then added back globing. I didn't want to make a "breaking" change again so left the type as string.

**Comment by davedoesdev** [comment]
Maybe support array in v5?
