### ISSUE TITLE
build package.nw folder with .exe file

### ISSUE THREAD

**Issue by abdeljalil09** [nwutils/nw-builder#756]
Hello
 in version 3.8.6 , i used to build the app without showing source code the app somehow it's hidden  , but now in version 4 i can see the source code in package.nw , is there a way to bundle it in .exe file

![image](https://user-images.githubusercontent.com/101262837/211020131-ce723897-531f-4002-99db-95fa3bd7d539.png)

**Comment by sysrage** [comment]
If you're referring to the following, don't do it. It's considered bad practice, it slows down your application startup time, and doesn't actually protect the source code.

You can manually "protect" the code using `nwjc`: https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

**Comment by abdeljalil09** [comment]
i mean in version 3.8.6 the build folder is as follow now package.nw and the app works well

![image](https://user-images.githubusercontent.com/101262837/211023545-bd3c6322-a36c-441e-88ff-9dce4a620f58.png)

but in version 4 the source code the app is in package.nw

**Comment by sysrage** [comment]
The source **is** in that package. It's a zip file appended to `sponsorsapp.exe`. The first link I provided above explains how it works, but it should not be used. Again, this source code is **not** protected. Anybody can extract it and view it.

**Comment by abdeljalil09** [comment]
ahh i see i understand now , i have used the second link to "protect" the code thank you
