### ISSUE TITLE
Source code protection

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwutils/nw-builder#757]
### Issue Type

- [ ] Bug Fix
- [x] Feature
- [ ] Other

### Current/Missing Behaviour

Source code protection is manually donr by user.

### Expected/Proposed Behaviour

Let `nw-builder` automatically handle it.

### Additional Info

https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Protect%20JavaScript%20Source%20Code/

- Operating System: N/A
- Node version: N/A
- NW.js version: N/A
- Repro link: N/A
- ...

**Comment by sysrage** [comment]
Super interested to see if you have a solution for this, but I have a hard time seeing how it can be done for anything but the most basic app.

**Comment by zkrige** [comment]
currently I use nwjc to compile a bunch of our js to bin files. Unfortunately I can't compile all the node modules, but its better than nothing

**Comment by ayushmanchhabra** [comment]
See https://github.com/nwutils/nw-builder/commit/9a92688d848a83a8317196c254009a6c1eeffa44
