### ISSUE TITLE
manifest.json not being downloaded due to inexistent cache directory

### ISSUE THREAD

**Issue by dominickbrasileiro** [nwutils/nw-builder#770]
### Issue Type

- [X] Bug Fix
- [ ] Feature
- [ ] Other

### Current/Missing Behaviour
Currently, the `cache` directory is not created when running the nwbuild CLI, resulting in the error below:
![image](https://user-images.githubusercontent.com/50509793/212564596-7bf8ead1-3284-49b7-bc9c-cd1aef7c0e66.png)

### Expected/Proposed Behaviour
Add a step to create the cache directory if it doesn't exist.

### Additional Info

- Operating System: Ubuntu 22.04
- Node version: v18.13.0
- NW.js version: 4.0.7

**Comment by tharatau** [comment]
https://github.com/nwutils/nw-builder/blob/d39a6d345edead51ca74c726f44560d554697c2c/src/nwbuild.js#L147-L156

Looks like the create cache dir code is after the `getReleaseInfo` info command which leads to this error.

**Comment by dominickbrasileiro** [comment]
hmm, but if the cache dir is not created before the `getManifest` function call, the `manifest.json` and SDK are never downloaded. 

I opened a PR creating the cache dir before knowing this info, but you can close it if it's wrong.

what do you suggest?

**Comment by tharatau** [comment]
> Create cache code:
> 
> https://github.com/nwutils/nw-builder/blob/d39a6d345edead51ca74c726f44560d554697c2c/src/nwbuild.js#L147-L156
> 
> Get release info code:
> 
> https://github.com/nwutils/nw-builder/blob/d39a6d345edead51ca74c726f44560d554697c2c/src/nwbuild.js#L138-L142
> 
> Looks like the create cache dir code is after the `getReleaseInfo` info command which leads to this error.

I guess my intuition was wrong. Something weird is going on. I'll dig into this.

**Comment by tharatau** [comment]
> hmm, but if the cache dir is not created before the `getManifest` function call, the `manifest.json` and SDK are never downloaded.
> 
> I opened PR #771 creating the cache dir before knowing this info, but you can close it if it's wrong.
> 
> what do you suggest?

This also does not seem to work:

```shell
ayushmxn@Tau:~/tharatau/nw/nw-builder$ npm run demo:nix

> nw-builder@4.0.7 demo:nix
> cd ./test/e2e && node nix.js

[ DEBUG ] 2023-01-15T20:45:44.469Z nwbuild property is not defined in package.json
[ DEBUG ] 2023-01-15T20:45:44.470Z Cache directory does not exist locally
[ DEBUG ] 2023-01-15T20:45:44.470Z Creating cache directory /home/ayushmxn/tharatau/nw/nw-builder/test/e2e/cache
[ DEBUG ] 2023-01-15T20:45:44.471Z Manifest file does not exist locally
[ DEBUG ] 2023-01-15T20:45:44.471Z Downloading latest manifest file under /home/ayushmxn/tharatau/nw/nw-builder/test/e2e/cache
[ DEBUG ] 2023-01-15T20:45:45.051Z Succesfully cached manifest metadata
[ DEBUG ] 2023-01-15T20:45:45.053Z Store manifest metadata in memory
[ DEBUG ] 2023-01-15T20:45:45.055Z Search for latest specific release data
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir './build/nix'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: './build/nix'
}

Node.js v18.13.0
```
