### ISSUE TITLE
DMG installer

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwutils/nw-builder#801]

**Comment by TinsFox** [comment]
Now I use [this tool](https://www.npmjs.com/package/appdmg) to build DMG installer

Do you have any new ideas about this @ayushmanchhabra ?

I wonder if nw-build could expose a plugin mechanism that would allow the user to decide if they want to add a file that subsequently generates a DMG installer. I'm not sure if this would work.

**Comment by sysrage** [comment]
Ooh, a plugin system is a good idea. Let users choose between [appdmg](https://www.npmjs.com/package/appdmg), [innosetup](https://www.npmjs.com/package/innosetup), [nsis](https://www.npmjs.com/package/makensis), etc.

**Comment by ayushmanchhabra** [comment]
The idea for dmg installer was to use the appdmg package - I must have forgotten to add that in the issue description. Since I don't have a Mac, I was unable to locally test and put it off for later.

@sysrage @TinsFox would you be willing to contribute this feature?

**Comment by TinsFox** [comment]
@ayushmanchhabra Of course, I'm glad I could help

**Comment by ayushmanchhabra** [comment]
@TinsFox Thanks! Can I assign this issue to you?

Here are my initial thoughts:

```javascript
nwbuild({
  version: "latest",
  platform: "osx",
  mode: "package",
  installer: "dmg", // maybe add "mas" in the future
});
```

This would allow us to add more installers for different platforms in the future. Also setting `options.mode` to `package` would imply that the `build` mode is invoked before `package`. I'm working on adding AppImage for Linux on a local branch. Let me know if you would like to wait for that first so there is something to work off.

**Comment by BrianBothwell** [comment]
What about:
```js
import dmgPackager from 'nw-dmg-packager';

nwbuild({
  version: "latest",
  platform: "osx",
  mode: "package",
  installer: dmgPackager
  });
  ```
  
Users could then build their own packaging plugin that handles everything. You'd simply need to define what values are passed to `dmgPackager()` when called. This would be values needed to create the installer (build directory, name, version, copyright strings, etc.).

**Comment by sysrage** [comment]
What about:
```js
import dmgPackager from 'nw-dmg-packager';

nwbuild({
  version: "latest",
  platform: "osx",
  mode: "package",
  packager: dmgPackager
  });
  ```
  
Users could then build their own packaging plugin that handles everything. You'd simply need to define what values are passed to `dmgPackager()` when called. This would be values needed to create the installer (build directory, name, version, copyright strings, etc.).

Sorry for double post. Used wrong GitHub account.

**Comment by TinsFox** [comment]
@ayushmanchhabra 

I'm not sure whether I will continue to use nwjs for development in the future. I encountered some problems when configuring the windows development environment (this is not a problem with nwjs, and some other dependent libraries are not friendly to windows support).

But when there is progress  I would love to test this part of the functionality.

**Comment by TinsFox** [comment]
> What about:
> ```js
> import dmgPackager from 'nw-dmg-packager';
> 
> nwbuild({
>   version: "latest",
>   platform: "osx",
>   mode: "package",
>   packager: dmgPackager
>   });
>   ```
>   
> Users could then build their own packaging plugin that handles everything. You'd simply need to define what values are passed to `dmgPackager()` when called. This would be values needed to create the installer (build directory, name, version, copyright strings, etc.).
> 
> If desired, `nw-builder` can come with some of these plugins. Otherwise, it's up to users to build/maintain them.
> 
> Sorry for double post. Used wrong GitHub account.

I am not sure that the input of other libraries seems to be the same as nw-dmg-packager. If it is different, a conversion needs to be done inside nwjs. You cannot directly pass a function into it. Maybe an enumerated string will be more suitable.

**Comment by sysrage** [comment]
> I am not sure that the input of other libraries seems to be the same as nw-dmg-packager. If it is different, a conversion needs to be done inside nwjs. You cannot directly pass a function into it. Maybe an enumerated string will be more suitable.

I think maybe you misunderstand my suggestion. The package `nw-dmg-packager` does not exist (yet). It is a theoretical "plugin" that can be used with `nw-builder`. Ideally there would be `nw-dmg-packager`, `nw-iss-packager`, `nw-nsis-packager`, etc. Some could be exported by `nw-builder` as "official" plugins, but this would allow users to build any packager they wanted.

**Comment by ayushmanchhabra** [comment]
See https://github.com/nwutils/nw-builder/commit/9a92688d848a83a8317196c254009a6c1eeffa44
