### ISSUE TITLE
User-passed-in options in options.app are not respected

### ISSUE THREAD

**Issue by williamwang96** [nwutils/nw-builder#812]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
The options passed into the `app` object are obliterated before being parsed.
https://github.com/nwutils/nw-builder/blob/bf7a53d69bfed59cc5f0833c50e91fca067b9a71/src/util/parse.js#L31

### Expected/Proposed Behaviour
Not sure if this was the intended code, but it worked for me after I updated to this.
![image](https://user-images.githubusercontent.com/18428483/223582568-0deb0ed3-9e59-4bdd-8c79-f1fa553e691e.png)

### Additional Info

- Package version: 4.1.0-beta.3
- Operating System: Windows 10
- Node version: v18.14.2
- NW.js version: v0.72.0

**Comment by tharatau** [comment]
Definately not intended! PR would be great

**Comment by williamwang96** [comment]
Will create a PR today or tomorrow.
