### ISSUE TITLE
Hardcoded path to .exe doesn't work for rcedit

### ISSUE THREAD

**Issue by williamwang96** [nwutils/nw-builder#813]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
For Windows builds, rcedit isn't doing anything.

### Expected/Proposed Behaviour
These two lines are probably better off to use a platform-independent solution. Interestingly the first line still works but not the second.
https://github.com/nwutils/nw-builder/blob/bf7a53d69bfed59cc5f0833c50e91fca067b9a71/src/bld/winCfg.js#L40
and
https://github.com/nwutils/nw-builder/blob/bf7a53d69bfed59cc5f0833c50e91fca067b9a71/src/bld/winCfg.js#L42 

I updated the second line to be this and it worked for me.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/18428483/223586673-f1744a61-7e1e-4bbd-949f-6c42ea4bfe49.png">

- Package version: 4.1.0-beta.3
- Operating System: Windows 10
- Node version: v18.14.2
- NW.js version: v0.72.0

**Comment by tharatau** [comment]
Must have missed using node path here. PR would be great!

**Comment by williamwang96** [comment]
Will create a PR today or tomorrow.
