### ISSUE TITLE
Cache never expires

### ISSUE THREAD

**Issue by sysrage** [nwutils/nw-builder#822]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

If you have an old `manifest.json` file in your `cache` directory, it's never updated. So, if a new version of NW.js comes out builds will fail.

### Expected/Proposed Behaviour

If using a cache, it needs to expire at some point.

### Additional Info

- Package version: 4.1.1

**Comment by williamwang96** [comment]
would it be an acceptable fix to always download `manifest.json`? It's very lightweight and shouldn't be cached anyways. I can work on a PR if the fix sounds good to you @tharatau .

**Comment by tharatau** [comment]
@williamwang96 My motivation for caching `manifest.json` was to allow builds without network (if the relevant nw binary is already downladed, that is). Ideally we redownload `manifest.json` when connected to network and don't while not connected to network.
