### ISSUE TITLE
Error: package.json not found in srcDir file glob patterns.

### ISSUE THREAD

**Issue by kipBO** [nwutils/nw-builder#832]
I noticed this was already reported but also noticed there was a fix already. But still I get this error how can I fix this?

**Comment by sysrage** [comment]
Show your nwbuild configuration object. What are you using for `srcDir` and do you have `glob` set to `false`?

**Comment by sysrage** [comment]
> I'm following this tutorial: https://www.sitepoint.com/cross-platform-desktop-app-nw-js/ This part(run dev) is causing the error: `"scripts":{ "dev":"nw src/", "prod":"nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/" }`

That tutorial is old and out-dated. The nw-builder API has changed. The docs need work, but check the following for some examples:

- https://github.com/nwutils/nw-builder/blob/main/docs/migrate-v3-v4.md
- https://github.com/nwutils/nw-builder/blob/main/docs/mode-build.md
- https://github.com/nwutils/nw-builder/tree/main/docs

**Comment by tharatau** [comment]
I don't know about any beginners guides but I'd say start with [Getting Started with NW.js](https://nwjs.readthedocs.io/en/latest/For%20Users/Getting%20Started/) then go the [nw-builder docs](https://nwutils.io/nw-builder/)
