### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by ElPrudi** [nwutils/nw-builder#838]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Other

### Current/Missing Behaviour

Typescript does not recognize nw-builder as a module after installing it.

### Expected/Proposed Behaviour

It would be cool to have basic types when building nw as TypeScript becomes more and more mandatory to the working environment.

**Comment by TheJaredWilcurt** [comment]
We went down this path with `create-desktop-shortcuts` and found that Using TypeScript's supplied solutions actually didn't work well with the TS Engine or editors, so we instead added JSDoc Comments which supplied types and also documentation.

* https://github.com/nwutils/create-desktop-shortcuts/pull/69
  * This shows screenshots comparing the bad result you get when using TS or `.d.ts` files, and the much better result you get from JSDocs.

The solution looks like this:

* A single JS file that defines all the types:
  * [api-type-definitions.js](https://github.com/nwutils/create-desktop-shortcuts/blob/main/api-type-definitions.js)
  * The file exports out variables that have JSDoc comments on them
* Then in the files where the types are used, you import just those variables and apply then in the JSDoc comment:
  * [example](https://github.com/nwutils/create-desktop-shortcuts/blob/main/index.js#L21)

We have a linting rule in place in this repo to apply JSDocs to every function, but that has a high maintenance cost and has mostly been ignored while the codebase has been under constant change (understandable).

However, this GitHub issue request would only require applying the JSDoc comment blocks to the public facing API, not the entire codebase (much easier).

**Comment by ElPrudi** [comment]
I think only typing the main function and its options in a separate `index.d.ts.` file and referencing it inside the `package.json` is enough to fix the error.

I am not asking for complex type inference and strong typing, I just want to fix the errors and get some type suggestions while working.

**Comment by TheJaredWilcurt** [comment]
Yes, same idea, just better result and less effort. A single JS file that contains the types instead of importing in all of the overhead and slowness of TypeScript. Also much better auto-complete and hover text.

**Comment by TheJaredWilcurt** [comment]
Ran locally and everything is already set up. TS works, auto-complete works, hover text works. Can you explain in more detail what issue you are having? @ElPrudi

**Comment by ElPrudi** [comment]
`Cannot find module 'nw-builder' or its corresponding type declarations. ts(2307)`

I have installed it and it is in my node modules folder. Since the package.json does not contain referenced types and there is no separate d.ts file, Typescript cannot find the types.

If you run it locally, allow js in your tsconfig, and don't use it as a node module, Typescript might derive it on its own. You may need to link it in your repo as a node module for it not to work.

**Comment by TheJaredWilcurt** [comment]
@ElPrudi I was able to reproduce it. I've created a branch that fixed it (at least for me), feel free to try it out yourself.

https://github.com/nwutils/nw-builder/pull/840

**Comment by ElPrudi** [comment]
Nope, still not. Try downloading your branch:
```json
"dependencies": {
   "nw-builder": "nwutils/nw-builder#entry-docs"
}
```
No TypeScript says:
```
Could not find a declaration file for module 'nw-builder'. '<project-path>/node_modules/.pnpm/github.com+nwutils+nw-builder@7e4512e0d47e75d61689dae0d34ca50eb1344a19_glob@8.1.0/node_modules/nw-builder/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nw-builder` if it exists or add a new declaration (.d.ts) file containing `declare module 'nw-builder';`ts(7016)
```

Like i said: No .d.ts file, no types.

To link the types inside your package.json for TypeScript to read, use:
```json
{
    "type": "./index.d.ts."
}
```

**Comment by tharatau** [comment]
@ElPrudi what editor are you using? I'm open to maintaining a type def file since we only export a single function.

**Comment by ElPrudi** [comment]
I use VSCode with the most popular TypeScript extensions.

**Comment by TheJaredWilcurt** [comment]
Should be good now. I had to update the `files` list in the `package.json` to get it to work via `npm install`

**Comment by tharatau** [comment]
@ElPrudi tested locally and works for me

**Comment by ElPrudi** [comment]
Im sorry, but no. I don't know what configuration you used, but it still complains about the missing `.d.ts` file. After setting
```json
{
  "exports": {
    "default": "./index.js",
    "types": "./index.d.ts"
  },
}
```

and only after creating a stub `.d.ts` file, it stopped complaining.
```typescript
declare function nwBuild(options: Record<string, unknown>): Promise<unknown>
export default nwBuild
```
(There is no need for `async` in a `.d.ts` file as long as the return type is `Promise<T>`)

My ts config:
```json
{
    "compilerOptions": {
        "rootDir": "src",
        "outDir": "dist",
        "module": "ESNext",
        "moduleResolution": "node",
        "target": "es2022",
        "forceConsistentCasingInFileNames": true,
        "preserveConstEnums": true
        "removeComments": true,
        "stripInternal": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "lib": ["es2022", "dom", "ESNext", "WebWorker", "ScriptHost"],
        "types": ["node"],
        "strict": true
    },
    "exclude": ["./node_modules", "./typings", "./dist", ".*/"],
    "include": ["./src/**/*.ts", "./src/**/*.d.ts"]
}
```

**Comment by TheJaredWilcurt** [comment]
What is your goal?

1. Have auto-complete as you type (should work)
1. Have documentation on hover (should work)
1. Have your source code checked against the TypeScript Compiler (on you)
1. Trying to compile the source code of the dependencies in your node modules using TypeScript (good luck with that)

**Comment by ElPrudi** [comment]
It's simple: JSDoc does not work in a strict TypeScript environment.

But since you're already throwing a tantrum about it because your minimal effort of trying to patch it does not work, even after giving all the steps and configuration to make it work, its easier for me to create my own version of nw-builder than to explain to a child why TypeScript is a important part of the today's workflow.

**Comment by TheJaredWilcurt** [comment]
Cool, works for me :)

**Comment by TheJaredWilcurt** [comment]
Oh yeah! @ElPrudi you might want to fork https://github.com/evshiron/nwjs-builder-phoenix

It's pretty decent, but no longer maintained. No one wanted to take over the project and have to deal with Classes written in TypeScript. But that sounds like your cup of tea, so may be a good fit.

**Comment by tharatau** [comment]
@ElPrudi made a basic tsd file. Feel free to open a PR if you find anything off.

**Comment by TheJaredWilcurt** [comment]
@tharatau the docs say the file can be auto generated from JSDocs. If that's true, I don't see why they need you to do it at all, they should just use it as the source of truth like they do everywhere else. TS is very dumb. Anyways, I wouldn't put in the effort to support that, but if you want to, go for it:

* https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by tharatau** [comment]
> https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

Interesting, was not aware. I have no problem maintaining it since its just one function.
