### ISSUE TITLE
Glob Issue: cp EINVAL src and dest is same

### ISSUE THREAD

**Issue by ReiFan49** [nwutils/nw-builder#868]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
Current behavior "resolves" the path with those 3 arguments, however if one of them is an absolute path, everything breaks.
https://github.com/nwutils/nw-builder/blob/6623963bdc9fb8d291a24cec1c95511daa96e644/src/bld/build.js#L57-L63

![image](https://github.com/nwutils/nw-builder/assets/9847780/c702b23c-4470-466e-8e4d-01d3d2c0574a)

After some deep inspection, I found out the **first item after the globbed file list turned absolute.**
![image](https://github.com/nwutils/nw-builder/assets/9847780/246a148d-3e8d-4b20-9715-1b1635211145)

### Expected/Proposed Behaviour
Globbed file list should not have any absolute reference if they don't have in the first place.

### Additional Info

- Package version: 4.2.0
- Operating System: Linux
- Node version: v16.20.0
- NW.js version: 8.19.4
- Repro link:

**Comment by A9U3HC** [comment]
Thanks for the bug report! I noticed you have a branch which seems to fix this behaviour. Are you opento submitting a PR?

**Comment by ReiFan49** [comment]
~~I made that branch for quicker git npm install on Github Action~~

That branch is just band-aid solution which I may suspect the root of the problem is not on `build.js` file.

I would be fine if it's referred or cherry picked (for further testing) as I would wait until actual solution/patch to this problem instead.

**Comment by A9U3HC** [comment]
This is a [known issue](https://github.com/nwutils/nw-builder/issues/836). I got busy with life and let this issue slip through my fingers. I'll try to look at it this week!

**Comment by rocketVibes** [comment]
Any update on this?

**Comment by ayushmanchhabra** [comment]
@ReiFan49 Apologies for the delay, I've been working on it locally - should have a PR up in next 2 days.

**Comment by rocketVibes** [comment]
@ayushmanchhabra no worries. looking forward to it!

**Comment by ayushmanchhabra** [comment]
> That branch is just band-aid solution which I may suspect the root of the problem is not on build.js file.

@ReiFan49 Turns out you were right!

@rocketVibes Please try `v4.2.3-beta.1` and let me know if you run into any other issues.

**Comment by ayushmanchhabra** [comment]
@rocketVibes what's your use case for `verbatimSymlinks`? I've personally never needed it.

**Comment by rocketVibes** [comment]
I have a project that bundles up a JRE (from Zulu) alongside project files,
and the JRE folder has sym links to maintain the standard JRE structure. It
comes from Zulu that way.
