### ISSUE TITLE
Bug: osx64 build can't be signed - nwjs bundle format unrecognized

### ISSUE THREAD

**Issue by rocketVibes** [nwutils/nw-builder#882]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
After building osx64 project, results in code signing errors as seen [here](https://stackoverflow.com/questions/29271548/code-sign-error-bundle-format-unrecognized-invalid-or-unsuitable).

### Expected/Proposed Behaviour
Should be able to sign generated app without Xcode errors.

### Additional Info
```
/tmp/sign-mac-app/RfwWll/example-tool.app/Contents/MacOS/nwjs: bundle format unrecognized, invalid, or unsuitable

In subcomponent: /private/tmp/sign-mac-app/RfwWll/example-tool.app/Contents/Frameworks/nwjs Framework.framework
```

- Package version: 4.2.4
- Operating System: MacOS Ventura
- Node version: 18.16.0
- NW.js version: 0.70.0

**Comment by ayushmanchhabra** [comment]
@rocketVibes This looks like a NW.js related issue. There are a couple of threads related to code signing in the NW.js repo. Linking them below:

https://github.com/nwjs/nw.js/issues/6338
https://github.com/nwjs/nw.js/issues/7117

I'll look into this in the next couple days. Maybe something can be done on `nw-builder` side to improve DX.

**Comment by rocketVibes** [comment]
@ayushmanchhabra do you expect the folder named 'nwjs Framework.framework' to contain these non-relative symlinks? 
```
nwjs Framework.framework git:(upgrade_build_config) ✗ ls -la
total 0
drwxr-xr-x  7 rocketVibes staff  224 Jun 19 14:31 .
drwxr-xr-x  3 rocketVibes  staff   96 Jun 19 14:31 ..
lrwxr-xr-x  1 rocketVibes  staff  157 Jun 19 14:31 Helpers -> /Users/rocketVibes/Sandbox/example-tool/cache/nwjs-v0.70.0-osx-x64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/Current/Helpers
lrwxr-xr-x  1 rocketVibes  staff  159 Jun 19 14:31 Libraries -> /Users/rocketVibes/Sandbox/example-tool/cache/nwjs-v0.70.0-osx-x64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/Current/Libraries
lrwxr-xr-x  1 rocketVibes  staff  159 Jun 19 14:31 Resources -> /Users/rocketVibes/Sandbox/example-tool/cache/nwjs-v0.70.0-osx-x64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/Current/Resources
drwxr-xr-x  4 rocketVibes  staff  128 Jun 19 14:31 Versions
lrwxr-xr-x  1 rocketVibes  staff  164 Jun 19 14:31 nwjs Framework -> /Users/rocketVibes/Sandbox/example-tool/cache/nwjs-v0.70.0-osx-x64/nwjs.app/Contents/Frameworks/nwjs Framework.framework/Versions/Current/nwjs Framework
```

**Comment by ayushmanchhabra** [comment]
@rocketVibes Are the Helper, Libraries, etc directories in `outDir` symlinking to the cache folder (after running build mode)?
Does setting [`vertabimSymlinks` to `false`](https://github.com/nwutils/nw-builder/commit/63d3b9ed2fb7efa90d4dade3770e10a43e8fe3cd) help?

**Comment by rocketVibes** [comment]
@ayushmanchhabra adding the verbatimSymlinks option to true preserves the relative paths which is causing at least parrt of the issue. Made a PR for this addition.
