### ISSUE TITLE
[osx64] Unable to set icon - results in blank icon

### ISSUE THREAD

**Issue by rocketVibes** [nwutils/nw-builder#895]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
Setting icon as follows results in blank XCode icon being used for generated app.
```
await nwbuild({
        mode: 'build',
        version: '0.70.0',
        flavor: 'normal',
        platform: 'osx',
        arch: 'x64',
        srcDir: './Settings.json ./package.json ./config.json dist/**',
        outDir: './build/example-tool/osx64',
        app: {
            name: 'example-tool',
            icon: './dist/assets/images/example-tool.icns',
        }
    });
```

### Expected/Proposed Behaviour
example-tool.icns file should be present in Info.plist file and should be displayed icon image. 

### Additional Info

- Package version: 4.3.0
- Operating System: macOS ventura 13.4
- Node version: 18.16.0
- NW.js version: 0.70.0

**Comment by ayushmanchhabra** [comment]
https://nwutils.io/nw-builder/api-osx.html#osxrc-object
For MacOS platform, the `options.app.*` properties are slightly different.

**Comment by rocketVibes** [comment]
@ayushmanchhabra here is what I am setting in my package.json:
```
"window": {
    "title": "Example Tool",
    "toolbar": false,
    "frame": true,
    "width": 1200,
    "height": 800,
    "min_width": 750,
    "min_height": 550,
    "position": "center",
    "icon": "./dist/assets/images/example_tool.icns",
    "show": true
  },
```
I am still not seeing any icon but the blank XCode icon. I appreciate your quick responses *so* much. Apologies for so much back and forth!

**Comment by rocketVibes** [comment]
Also, I tried to update the fields in app.options:
```
await nwbuild({
        mode: 'build',
        version: '0.70.0',
        flavor: 'normal',
        platform: 'win',
        arch: "x64",
        outDir: './build/example-tool/win64',
        srcDir: './Settings.json ./package.json ./config.json ./dist/**,
        app: {
            name: 'example-tool',
            CFBundleDisplayName: 'Example Tool',
            CFBundleVersion: version,
            CFBundleShortVersionString: version,
            companyName: 'rocketVibes International, Inc.',
            NSHumanReadableCopyright: `Copyright ${new Date().getFullYear()} rocketVibes International, Inc.  All rights reserved.`,
            originalFilename: 'example-tool.exe',
            icon: './dist/assets/images/example_tool.ico'
        }
    });
```

It appears that the English InfoPlist.strings CFBundleGetInfoString value (example path: /build/example-tool/osx64/example-tool.app/Contents/Resources/en.lproj) is overriding the NSHumanReadableCopyright value set in the Info.plist -- so the nwjs copyright is coming through instead of the one I set.

**Comment by ayushmanchhabra** [comment]
@rocketVibes I was able to reproduce. I'll look into why the icon is not being set!
