### ISSUE TITLE
Build fails with "package.json not found in srcDir file glob patterns" error

### ISSUE THREAD

**Issue by abhidaa1233** [nwutils/nw-builder#899]
### Issue Type

- [x] Bug Report

I am using "npm run prod" to generate the executable. Whenever I am trying to generate it throws error "package.json not found in srcDir file glob patterns". Tried downgrading different versions of nwjs, nw-build, nodejs, npm etc but didn't work out. In my project I am using I am using Angularjs, nodejs, html, css along with nwJs. I will provide information on my folder structure:

```shell
node_modules
src
src/app/
src/css/
src/lib/
src/index.html
src/package.json
package.json
```

package.json:
```json
{
"name": "My_Project",
"version": "1.0.0",
"description": "",
"main": "index.html",
"scripts": {
"dev": "nw src/",
"prod": "nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/src/"
},
"keywords": [],
"author": "",
"license": "ISC",
"devDependencies": {
"nw": "^0.76.1-sdk",
"nw-builder": "^4.2.3"
}
}
```
src/package.json:
```json
{
"name": "src",
"version": "1.0.0",
"description": "",
"main": "index.html",
"directories": {
"lib": "lib"
},
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"window": {
"title": "Office1",
"icon": "",
"toolbar": true,
"frame": true,
"resizable": true,
"width": 1200,
"height": 700,
"min_width": 1200,
"min_height": 700,
"fullscreen": false,
"position": "center"
},
"keywords": [],
"author": "",
"license": "ISC"
}
```

Stack Trace:
```shell
Error : [ ERROR ] 2023-07... package.json not found in srcDir file glob patterns.
file:///...My_Project_Path/node_modules/nw-builder/src/util/versionManifest.js:26
throw new Error("package.json not found in srcDir file glob patterns.");
```

### Current/Missing Behavior

Could not generate executable file

### Expected/Proposed Behavior

Normal smooth executable generation

### Additional Info

Operating System: Windows 10
NW.js Version: 0.76.1-sdk
nw-builder Version: 4.2.3

**Comment by ayushmanchhabra** [comment]
@abhidaa1233 If you're using v4, please update to the latest v4.3.1. 

`nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/src/`

This is the syntax for v3. For version 4, please see the updated docs:
https://nwutils.io/nw-builder/

**Comment by abhidaa1233** [comment]
@ayushmanchhabra I am new to nwJS and its a bit urgent, can you please provide some sample on what to use in package.json in version 4 onwards instead of "nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/src/".

**Comment by abhidaa1233** [comment]
I tried downgrading the nw-build version to 3.8.6 and nw version to 0.67.0 with old code but its giving another error:
> My_Project@1.0.0 prod
> nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/src/

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No files matching".] {
  code: 'ERR_UNHANDLED_REJECTION'
} 

@ayushmanchhabra normally npm run dev is working fine with all trials but "npm run dev" not working with either of the trials

**Comment by ayushmanchhabra** [comment]
@abhidaa1233 Try changing:
```shell
nwbuild --platform win --arch x64 --outDir dist/src/
```

To:
```shell
nwbuild --platform win --arch x64 --outDir dist/src --glob=false src
```

You need to specify which directory/directories `nw-builder` should parse as a NW.js project.

**Comment by abhidaa1233** [comment]
@ayushmanchhabra that did not work, giving the same error "Error: package.json not found in srcDir file glob patterns.". Is there any version conflict ? why it can't find package.json. Any other way to just generate the executable for windows 64?

**Comment by ayushmanchhabra** [comment]
@abhidaa1233 I was able to reproduce this - will look into it. Thanks for the bug report!

**Comment by abhidaa1233** [comment]
@ayushmanchhabra Ok. For temporary fix can you suggest any solution on how to generate the executable for atleast win 64? or give me any version combinations of nw, nw-build and nodejs etc so that it works

**Comment by ayushmanchhabra** [comment]
```shell
nwbuild --platform win --arch x64 --outDir dist/src --glob=false src
```
Upgrade to v4.3.2 and the above command should work

**Comment by abhidaa1233** [comment]
@ayushmanchhabra Thankx man, thankx a lot, it worked
