### ISSUE TITLE
libffmpeg not being installed into correct folder

### ISSUE THREAD

**Issue by zkrige** [nwutils/nw-builder#916]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
fetching ffmpeg doesn't seem to install it

### Expected/Proposed Behaviour
Fetching ffmpeg installs it in correct folder

### Additional Info
I'm seeing the original libffmpeg.dylib in the folders on macOS. It looks like its not being overwritten with the one from the community repo

**Comment by ayushmanchhabra** [comment]
You're right, I think I broke this in https://github.com/nwutils/nw-builder/commit/257350d0c00a647342f37fe7494d4121fb4c3bd1

**Comment by zkrige** [comment]
I see this was removed and and is no longer in use

`await replaceFfmpeg(options.platform, nwDir, ffmpegFile);`

It probably just needs to be put back

**Comment by ayushmanchhabra** [comment]
AH yes

**Comment by zkrige** [comment]
Maybe we should keep a ffmpeg folder in the cache dir like you do for nwjs? I think that's how nwjs-builder-phoenix used to do it

**Comment by zkrige** [comment]
Please reopen - this isn't working. I'll sort a fix for this shortly
