### ISSUE TITLE
linux platform builds with ffmpeg enabled fail with zlib error '[ ERROR ] incorrect header check'

### ISSUE THREAD

**Issue by LostBeard** [nwutils/nw-builder#960]
### Issue Type

- [X ] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
Building with linux platform fails for both arch x64 and ia32 when ffmpeg: true. The win platform for x64 and ia32 works with ffmpeg: true (or false.) I have not tested OSx builds.

This is the error it gives.
```
at Zlib.zlibOnError [as onerror] (node:zlib:189:17) {   
  errno: -3,   
  code: 'Z_DATA_ERROR',   
  level: 'error',   
  timestamp: '2023-10-11T19:58:14.650Z',   
  [Symbol(level)]: 'error',   
  [Symbol(message)]: '[ ERROR ] incorrect header check'   
}
```

### Expected/Proposed Behaviour
I expected the build to be successful in the same way the win build was.

### Additional Info

Build options that fail (only when ffmpeg: true, and platform: 'linux'):  
```
{
        srcDir: "./app",
        mode: "build",
        version: "stable",
        flavor: "normal",
        platform: "linux",
        arch: "x64",
        cache: true,
        ffmpeg: true,
        glob: false,
        app: {
            company: "Some Company",
            fileDescription: "Process Name",
            productName: "Some Product",
            legalCopyright: "Copyright (c) 2023",
        },
}
```

- Package version: ^4.4.1
- Operating System: Win 10 Home
- Node version: v20.5.1
- NW.js version: v0.80.0

**Comment by ayushmanchhabra** [comment]
@LostBeard I was able to resolve this. Should have the fix out in a new release on Monday.

**Comment by LostBeard** [comment]
Awesome. Thank you!
