### ISSUE TITLE
Enabling and disabling `options.ffmpeg` still uses community FFmpeg on successive build

### ISSUE THREAD

**Issue by LostBeard** [nwutils/nw-builder#963]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour
When the build option "ffmpeg" is set to true the community ffmpeg build is extracted to the cached NWjs folder for the given platform on build (and it builds as expected.) If the build option "ffmpeg" is then set to false, the app is still built using the ffmpeg community build. You can check the size of the ffmpeg.dll files to verify this.

### Expected/Proposed Behaviour
When ```{ ffmpeg: false }``` the build should use the default ffmpeg and when ```{ ffmpeg: true }``` use the community build, regardless of the previous value.

### Additional Info
The build option "cache" was set to true in the test builds.

I have tested some changes to get the desired result. I should be able to get a pull request up tomorrow. 

Essentially I disabled the call to replaceFfmpeg (```.then(async () => await replaceFfmpeg(platform, nwDir))```) in get.js and instead of extracting to nwDir (the NWjs cache folder) ffmpeg is extracted to its own cache folder. Then after a build() mode call, a slightly modified replaceFfmpeg is called to copy over the correct platform file from the ffmpeg cache folder to the build folder.

Looking at it though, some modifications would need to be made to also work in run mode. 

Build options

- Package version: 4.4.2
- Operating System: Win 10 Home
- Node version: v20.5.1
- NW.js version: v0.80.0

**Comment by ayushmanchhabra** [comment]
My thinking is we can tweak the caching implementation for NW.js binaries.

Assume cache is enabled and ffmpeg is enabled. Download compressed nwjs and ffmpeg files. Remove previous decompressed files. Decompress both nwjs and ffmpeg. _Do not remove the compressed files after decompression._ (This is the current behaviour)

Now disable ffmpeg. nwjs is decompressed only. This way we mitigate your current situation and config matches the files placed.

What do you think?

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/npm-installer#retrieve-binaries-from-custom-download-location-or-file-path
This would also allow `nw` npm package to treat the `options.cacheDir` as a local file server.

**Comment by ayushmanchhabra** [comment]
We will also be able to retry decompression on 'central directory not found` ZIP error.

**Comment by LostBeard** [comment]
Those changes look good. 👍
