### ISSUE TITLE
Rename MacOS Helpers

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwutils/nw-builder#966]
### Discussed in https://github.com/nwutils/nw-builder/discussions/930

<div type='discussions-op-text'>

<sup>Originally posted by **ayushmanchhabra** August 22, 2023</sup>
Refs: https://github.com/nwutils/nw-builder/issues/897#issuecomment-1630190132
Refs: #705

@zkrige I don't have a MacOS to test this on. Are you up for creating a PR to test this?
</div>

**Comment by zkrige** [comment]
yes I'll test this as soon as I get a chance

**Comment by sysrage** [comment]
Unless Ayush changed something again recently, I already teste this and it failed.

**Comment by ayushmanchhabra** [comment]
See https://github.com/nwutils/nw-builder/commit/9a92688d848a83a8317196c254009a6c1eeffa44
